### ISSUE TITLE
Mod Menu conflict

### ISSUE THREAD

**Issue by cutieshy** [Wurst-Imperium/Wurst7#1018]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

Conflicted with Mod Menu, results in a crash every time you pause, removed every mod but Mod Menu and Wurst and it still crashes. 

### Repro steps

1. Install Wurst + Mod Menu for MC version 1.21
2. launch a world
3. try to escape, crash

### Wurst Client version

7.43.1

### Minecraft version

1.21

### Crash report (if applicable)

```plaintext
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-06-18 15:38:56
Description: Someone deleted the Feedback button!

java.lang.IllegalStateException
	at net.minecraft.class_433.addWurstOptionsButton(class_433.java:1109)
	at net.minecraft.class_433.handler$zpa000$wurst$onInitWidgets(class_433.java:1053)
	at net.minecraft.class_433.method_20543(class_433.java:121)
	at net.minecraft.class_433.method_25426(class_433.java:68)
	at net.minecraft.class_437.method_25423(class_437.java:309)
	at net.minecraft.class_310.method_1507(class_310.java:1143)
	at net.minecraft.class_310.method_20539(class_310.java:1718)
	at net.minecraft.class_309.method_1466(class_309.java:451)
	at net.minecraft.class_309.method_22678(class_309.java:499)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:499)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_433.addWurstOptionsButton(class_433.java:1109)
	at net.minecraft.class_433.handler$zpa000$wurst$onInitWidgets(class_433.java:1053)
	at net.minecraft.class_433.method_20543(class_433.java:121)
	at net.minecraft.class_433.method_25426(class_433.java:68)
	at net.minecraft.class_437.method_25423(class_437.java:309)
	at net.minecraft.class_310.method_1507(class_310.java:1143)
	at net.minecraft.class_310.method_20539(class_310.java:1718)
	at net.minecraft.class_309.method_1466(class_309.java:451)
	at net.minecraft.class_309.method_22678(class_309.java:499)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:499)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)

-- Uptime --
Details:
	JVM uptime: 44.953s
	Wall uptime: 30.690s
	High-res time: 29.347s
	Client ticks: 408 ticks / 20.400s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['redacted'/43, l='ClientLevel', x=-454.50, y=70.00, z=-217.50]]
	Chunk stats: 961, 55
	Level dimension: minecraft:overworld
	Level spawn location: World: (-464,63,-208), Section: (at 0,15,0 in -29,3,-13; chunk contains blocks -464,-64,-208 to -449,319,-193), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 67 game time, 67 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 120

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, modmenu, wurst

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 4053595216 bytes (3865 MiB) / 5242880000 bytes (5000 MiB) up to 5242880000 bytes (5000 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 970
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 4096.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5599
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 22854.32
	Virtual memory used (MiB): 18103.22
	Swap memory total (MiB): 6544.74
	Swap memory used (MiB): 377.99
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 4130.16, total: 476823.00
	Space in storage for workdir (MiB): available: 4130.16, total: 476823.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms5000m -Xmx5000m
	Fabric Mods: 
		fabric-api: Fabric API 0.100.1+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.65+b559734490
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b9990
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a790
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a790
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.11+b559734490
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.12+7f945d5b90
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.2.1+d153f34490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a790
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.22+6a6dfa1990
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.6+16c4ae2590
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9990
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b9990
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8c90
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92190
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0+00ab0a6390
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.9+98a7dbbb90
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.9+6573ed8c90
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c90
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b90
			fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0+686dcdce90
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.10+d132107690
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c90
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.8+6573ed8c90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.21+b9828ba390
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6b90
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.3+cc9f121a90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b559734490
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d132107690
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f34490
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.3+b559734490
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.78+b559734490
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.12+b559734490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8c90
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: Java HotSpot(TM) 64-Bit Server VM 21
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.0
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		wurst: Wurst Client v7.43.1-MC1.21
	Launched Version: 1.21
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 970/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.99, NVIDIA Corporation
	Window size: 854x480
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, modmenu, wurst
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['redacted'/43, l='ServerLevel[New World]', x=-454.50, y=70.00, z=-217.50]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -3418051382999237820
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\shy\Programs\MultiMC\instances\wurst crash log generator\.minecraft\crash-reports\crash-2024-06-18_15.38.56-client.txt
Process exited with exit code -1 (0xffffffffffffffff).
```

**Comment by cutieshy** [comment]
btw if anyone else has this issue; disable wurst, go back in, change mod menu to be an icon. Relaunch with wurst and it should be good 👍 (this didn't happen in 1.20 for some reason)
