### ISSUE TITLE
Cannot edit auto librarian books

### ISSUE THREAD

**Issue by FakeSiryakari** [Wurst-Imperium/Wurst7#1028]
### Pre-reporting checklist

- [x] I have searched existing issues and didn't find any previous reports of this bug.
- [x] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [x] I have tried removing all other mods and the bug still happens.

### Description

Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1887.comp_2686()" because "enchantment" is null

### Repro steps

1. download mods 
![image](https://github.com/Wurst-Imperium/Wurst7/assets/105744131/290d80ca-3698-473b-b81f-389d1b253e58)
![image](https://github.com/Wurst-Imperium/Wurst7/assets/105744131/a36ef921-2a07-415c-9935-490931f89486)
2. install fabric 1.21
3. launch mc
4. try to edit books in auto librarian (both survival and multiplayer

### Wurst Client version

7.43.1

### Minecraft version

1.21

### Crash report (if applicable)

```plaintext
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-06-25 13:24:44
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1887.comp_2686()" because "enchantment" is null
	at net.wurstclient.hacks.autolibrarian.BookOffer.getEnchantmentNameWithLevel(BookOffer.java:70)
	at net.wurstclient.clickgui.screens.EditBookOffersScreen$ListGui.renderItem(EditBookOffersScreen.java:273)
	at net.wurstclient.util.ListWidget.renderList(ListWidget.java:410)
	at net.wurstclient.util.ListWidget.method_25394(ListWidget.java:180)
	at net.wurstclient.clickgui.screens.EditBookOffersScreen.method_25394(EditBookOffersScreen.java:190)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$268(class_757.java)
	at net.minecraft.class_757.wrapOperation$bij000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.wurstclient.hacks.autolibrarian.BookOffer.getEnchantmentNameWithLevel(BookOffer.java:70)
	at net.wurstclient.clickgui.screens.EditBookOffersScreen$ListGui.renderItem(EditBookOffersScreen.java:273)
	at net.wurstclient.util.ListWidget.renderList(ListWidget.java:410)
	at net.wurstclient.util.ListWidget.method_25394(ListWidget.java:180)
	at net.wurstclient.clickgui.screens.EditBookOffersScreen.method_25394(EditBookOffersScreen.java:190)
	at net.minecraft.class_437.method_47413(class_437.java:117)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$268(class_757.java)
	at net.minecraft.class_757.wrapOperation$bij000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586)

-- Screen render details --
Details:
	Screen name: net.wurstclient.clickgui.screens.EditBookOffersScreen
	Mouse location: Scaled: (617, 140). Absolute: (1234.000000, 280.000000)
	Screen size: Scaled: (960, 493). Absolute: (1920, 986). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 195.803s
	Wall uptime: 160.350s
	High-res time: 145.059s
	Client ticks: 1920 ticks / 96.000s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Pohodovej_rybar'/84, l='ClientLevel', x=-97.67, y=76.00, z=-79.30]]
	Chunk stats: 256, 45
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,101,0), Section: (at 0,5,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 18105 game time, 1728 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 7

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/NightVision_1.13+.zip, fabric, appleskin, caffeineconfig, carpet, cloth-config, essential, essential-container, essential-loader, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, immediatelyfast, inventoryprofilesnext, iris, itemscroller, libipn, litematica, malilib, minihud, modmenu, reeses-sodium-options, seedcrackerx, sodium, sodium-extra, sound_physics_remastered, tweakeroo, uiutils, voicechat, wthit, wurst, xaerominimap, xaeroworldmap, Essential Assets, essential

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 348269736 bytes (332 MiB) / 1006632960 bytes (960 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.71
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.2125
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 14723.21
	Virtual memory used (MiB): 8803.71
	Swap memory total (MiB): 6656.00
	Swap memory used (MiB): 518.23
	Space in storage for jna.tmpdir (MiB): available: 58429.77, total: 243470.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 58429.77, total: 243470.00
	Space in storage for io.netty.native.workdir (MiB): available: 58429.77, total: 243470.00
	Space in storage for java.io.tmpdir (MiB): available: 58429.77, total: 243470.00
	Space in storage for workdir (MiB): available: 58429.77, total: 243470.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 3.0.2+mc1.21
		badpackets: Bad Packets 0.8.1
		carpet: Carpet Mod 1.4.147+v240613
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.61
		elementa: Elementa 649
		essential: Essential 1.3.2.7+g7245995b31
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		fabric-api: Fabric API 0.100.1+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.65+b559734490
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b9990
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a790
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a790
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa1990
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.11+b559734490
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.12+7f945d5b90
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.2.1+d153f34490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a790
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.22+6a6dfa1990
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.6+16c4ae2590
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9990
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b9990
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8c90
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc92190
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0+00ab0a6390
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.9+98a7dbbb90
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.9+6573ed8c90
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c90
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b90
			fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0+686dcdce90
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.10+d132107690
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c90
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.8+6573ed8c90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.21+b9828ba390
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6b90
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.3+cc9f121a90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b559734490
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d132107690
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f34490
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.3+b559734490
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.78+b559734490
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.12+b559734490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8c90
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		gammautils: Gamma Utils 1.9.20
		immediatelyfast: ImmediatelyFast 1.2.18+1.21
			net_lenni0451_reflect: Reflect 1.3.4
		inventoryprofilesnext: Inventory Profiles Next 2.0.0
		iris: Iris 1.7.1+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemscroller: Item Scroller 0.23.999-sakura.1
		java: OpenJDK 64-Bit Server VM 21
		libipn: libIPN 5.0.0
		litematica: Litematica 0.18.999-sakura.4
		malilib: MaLiLib 0.19.999-sakura.2
		minecraft: Minecraft 1.21
		minihud: MiniHUD 0.31.999-sakura.3
		modmenu: Mod Menu 11.0.0-beta.1
		org_jetbrains_annotations: annotations 23.0.0
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.21
		seedcrackerx: SeedCrackerX 2.15.0
		sodium: Sodium 0.5.9+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.21-1.4.3
		stackrefill: Stack Refill 4.4
		treeharvester: Tree Harvester 8.9
		tweakeroo: Tweakeroo 0.20.999-sakura.2
		uiutils: UI Utils 2.0.0
		universalcraft: UniversalCraft 342
		vigilance: Vigilance 297
		voicechat: Simple Voice Chat 1.21-2.5.16
		wise_elytra: Wise Elytra 1.1
		wthit: wthit 12.1.2
		wurst: Wurst Client v7.43.1-MC1.21
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.15.11-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Intel(R) HD Graphics 620 GL version 3.2.0 - Build 31.0.101.2125, Intel
	Window size: 1920x986
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Render Distance: 2/2 chunks
	Resource Packs: vanilla, file/NightVision_1.13+.zip (incompatible), fabric, appleskin (incompatible), caffeineconfig, carpet, cloth-config, essential (incompatible), essential-container, essential-loader, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, immediatelyfast, inventoryprofilesnext, iris, itemscroller, libipn, litematica, malilib, minihud, modmenu, reeses-sodium-options, seedcrackerx, sodium, sodium-extra, sound_physics_remastered, tweakeroo (incompatible), uiutils, voicechat, wthit, wurst, xaerominimap (incompatible), xaeroworldmap (incompatible)
	Current Language: en_us
	Locale: en_GB
	System encoding: Cp1250
	File encoding: UTF-8
	CPU: 4x Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Pohodovej_rybar'/84, l='ServerLevel[spedrun]', x=-97.67, y=76.00, z=-79.30]]
	Active Data Packs: vanilla, fabric, collective, fabric-convention-tags-v2
	Available Data Packs: bundle, collective, fabric, fabric-convention-tags-v2, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -4255528866752407162
```

**Comment by FakeSiryakari** [comment]
fix: deleted wurst folder in .minecraft
