### ISSUE TITLE
1.21.4 Incompatible

### ISSUE THREAD

**Issue by jurohn** [Wurst-Imperium/Wurst7#1091]
### Pre-reporting checklist

- [X] I have searched existing issues and didn't find any previous reports of this bug.
- [X] This bug still happens in the latest version of Wurst. I've made sure my installation is up to date.
- [X] I have tried removing all other mods and the bug still happens.

### Description

Crash on 1.21.4

### Repro steps

Latest fabric, latest fabric api, sodium, sodium extra, reeses sodium options.

### Wurst Client version

7.46.4

### Minecraft version

1.21.4

### Crash report (if applicable)

```plaintext
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-12-04 09:31:09
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_759 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at knot//net.minecraft.class_898.<init>(class_898.java:97)
	at knot//net.minecraft.class_310.<init>(class_310.java:623)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onApplySwingOffsetNotBlocking(Lnet/minecraft/class_742;FFLnet/minecraft/class_1268;FLnet/minecraft/class_1799;FLnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in wurst.mixins.json:HeldItemRendererMixin from mod wurst failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap Wurst-Client-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 13 more
```

**Comment by jurohn** [comment]
> Hey @jurohn,
> 
> Wurst is not incompatible with Minecraft 1.21.4 or with Sodium 0.6.2. Please clarify what you are referring to as "incompatible".

When i start up with these mods:

![image](https://github.com/user-attachments/assets/45eb3a71-59f5-468e-9a73-26fd7aef5fe6)

It crashes. With the crash report i posted.

**Comment by Alexander01998** [comment]
Well, of course. That's Wurst for Minecraft 1.21.3! 😄

![image](https://github.com/user-attachments/assets/c2632813-bcea-42c9-9777-880e7f9dae43)

**Comment by jurohn** [comment]
> Well, of course. That's Wurst for Minecraft 1.21.3! 😄
> 
> ![image](https://private-user-images.githubusercontent.com/10100202/392316334-c2632813-bcea-42c9-9777-880e7f9dae43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDU2MTMsIm5iZiI6MTczMzMwNTMxMywicGF0aCI6Ii8xMDEwMDIwMi8zOTIzMTYzMzQtYzI2MzI4MTMtYmNlYS00MmM5LTk3NzctODgwZTdmOWRhZTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA5NDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZWZjOTgwMWQ4MmYyNTQwMTJiYjZjY2Q4OWE0NjQ1NTA3ZmE0MDRmMTE2NDI3ZWIwNmVmYWIwNjhmZmM4ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.USuDe8GBIq46Bzi61D6Sr5013Vv-tDaJxcjf_FN4xCQ)

Im so sorry.
