### ISSUE TITLE
SafeWalk & SpeedHack makes me fall off blocks

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/Wurst7#127]
## Description
When I have SpeedHack and SafeWalk on, and when I walk without jumping, I fall off the edge of any block. I'm expecting that SpeedHack and SafeWalk don't let me fall off a block.

## Steps to reproduce
1. Turn on SpeedHack
2. Turn on SafeWalk
3. Walk off a block

## Versions
- Minecraft version: Fabric 1.15.2 (fabric load 0.8.5+build-199-1.15.2)
- Wurst version: Wurst v7.1.2

## Crash report
```java
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 6/19/20 11:00 AM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.class_309.method_1474(class_309.java:668)
	at net.minecraft.class_310.method_1574(class_310.java:1511)
	at net.minecraft.class_310.method_1523(class_310.java:964)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_309.method_1474(class_309.java:668)

-- Affected level --
Details:
	All players: 1 total; [class_746['privated name'/87, l='MpServer', x=3664.09, y=71.00, z=8985.35]]
	Chunk stats: Client Chunk Cache: 289, 112
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -2763547683665249892
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (224,64,208), Chunk: (at 0,4,0 in 14,13; contains blocks 224,0,208 to 239,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6700 game time, 6700 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:611)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:634)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1384641800 bytes (1320 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		com_github_kaptainwutax_latticg: LattiCG b2a338f7bd765dcd184136c2245ea5765b75edf8
		fabric: Fabric API 0.11.1+build.312-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+045efb460c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.2.1+e7a4edb30c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+3e5587510c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.0+3e5587510c
		fabricloader: Fabric Loader 0.8.5+build.199
		minecraft: Minecraft 1.15.2
		mm: Manningham Mills 2.0
		optifabric: Optifabric 1.0.0-beta8
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		seedcracker: Seed Cracker 0.1.0-beta
		wurst: Wurst Client v7.1.2-MC1.15.2
	Launched Version: fabric-loader-0.8.5+build.199-1.15.2
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) Iris(TM) Graphics 6100 GL version 2.1 INTEL-10.36.25, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
```

**Comment by XfedeX** [comment]
@NoNoTeal I had this issue too, but it seems to be fixed. If yes, please mark as solved.
