### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by duhanke** [Wurst-Imperium/Wurst7#141]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2020-07-02 17:21:27 CST
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wurst'!
    at Not Enough Crashes deobfuscated stack trace.(1.15.2+build.17)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
    at net.minecraft.client.MinecraftClient.redirect$zzm000$stopFabricInit(MinecraftClient:3030)
    at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:392)
    at net.minecraft.client.main.Main.main(Main:166)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/keybinding/v1/KeyBindingHelper
    at net.wurstclient.WurstClient.initialize(WurstClient.java:147)
    at net.wurstclient.WurstInitializer.onInitialize(WurstInitializer.java:27)
    at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    ... 11 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.keybinding.v1.KeyBindingHelper
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.15.2
  Minecraft Version ID: 1.15.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_251, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 121530384 bytes (115 MB) / 469762048 bytes (448 MB) up to 1073741824 bytes (1024 MB)
  CPUs: 2
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1024m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  Suspected Mods: Fabric Loader (fabricloader), Wurst Client (wurst)
  Fabric Mods: fabric: Fabric API 0.7.1+build.301-1.15
               fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
               fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
               fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+e40501d40c
               fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
               fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
               fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
               fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.4+ec951ea40c
               fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
               fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+003643510c
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.0.2+915c44630c
               fabricloader: Fabric Loader 0.8.9+build.203
               loadcatcher: Entrypoint Catcher 1.1.0
               malilib: MaLiLib 0.10.0-dev.20+beta.1
               minecraft: Minecraft 1.15.2
               mm: Manningham Mills 2.0
               notenoughcrashes: Not Enough Crashes 1.2.2+1.15.1
               optifabric: Optifabric 1.0.0-beta8
               org_slf4j_slf4j-api: slf4j-api 1.7.30
               org_slf4j_slf4j-simple: slf4j-simple 1.7.30
               org_zeroturnaround_zt-zip: zt-zip 1.14
               waila: Hwyla 1.9.19
               wurst: Wurst Client v7.3-MC1.15.2
  Launched Version: 1.15.2
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: NO CONTEXT
  GL Caps: 
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  CPU: <unknown>

**Comment by TNThacker2015** [comment]
Update fabric and fabric API.

**Comment by Alexander01998** [comment]
> Fabric API 0.7.1+build.301-1.15
> Fabric Loader 0.8.9+build.203

Outdated Fabric API version. (Fabric loader is fine.)

For detailed instructions, see: https://www.reddit.com/r/WurstClient/comments/hg6xce/cant_launch_the_game_read_this_first/
