### ISSUE TITLE
Xray doensn't work with Optifine and Optifabric installed

### ISSUE THREAD

**Issue by faseri** [Wurst-Imperium/Wurst7#174]
## Description
Xray doensn't work when Optifine and Optifabric installed. Instead it just renders the world fullbright-like

## Steps To Reproduce
1. Install Optifabric and Optifine.
2.  Join any world - no matter multi or single player
3.  Enable X-ray hack

## Screenshots / Videos (Optional)
Before: [https://i.imgur.com/JrnCu8T.png](https://i.imgur.com/JrnCu8T.png)
After: [https://i.imgur.com/BVwltOA.png](https://i.imgur.com/BVwltOA.png)
## Crash Report
```
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.class_309.method_1474(class_309.java:669)
	at net.minecraft.class_310.method_1574(class_310.java:1572)
	at net.minecraft.class_310.method_1523(class_310.java:994)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_309.method_1474(class_309.java:669)

-- Affected level --
Details:
	All players: 1 total; [class_746['faseri'/1910834, l='ClientLevel', x=9209.71, y=10.00, z=36138.35]]
	Chunk stats: Client Chunk Cache: 225, 121
	Level dimension: minecraft:overworld
	Level spawn location: World: (639,64,3112), Chunk: (at 15,4,8 in 39,194; contains blocks 624,0,3104 to 639,255,3119), Region: (1,6; contains chunks 32,192 to 63,223, blocks 512,0,3072 to 1023,255,3583)
	Level time: 152905 game time, 268544832 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:616)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:672)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 556815824 bytes (531 MB) / 2214592512 bytes (2112 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ConcGCThreads=2 -XX:ParallelGCThreads=8 -Xmx8192M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		fabric: Fabric API 0.15.1+build.380-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.3+0a55f37902
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.8.9+build.203
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0
		optifabric: Optifabric 1.1.0-beta2
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		wurst: Wurst Client v7.4-MC1.16.1
		xaeroworldmap: Xaero's World Map 1.8.0
	Launched Version: fabric-loader-0.8.9+build.203-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.02, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, programer_art, optifine
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz

```

**Comment by faseri** [comment]
Update: it hides water, pots, bed, signs, heads, banners, bell

**Comment by hrmorley34** [comment]
Other visual/performance mods have some similar problems:

[Sodium](https://github.com/jellysquid3/sodium-fabric) 0.1.0 seems to do the same fullbright and no-hide deal.
[Before](https://user-images.githubusercontent.com/10192165/90130881-1a3e1b00-dd63-11ea-91bc-6ee08851d8b6.png) / [After](https://user-images.githubusercontent.com/10192165/90130885-1c07de80-dd63-11ea-881a-da2c7e5a9c3f.png)

[Canvas Renderer](https://github.com/grondag/canvas) 1.0.871 does hide some blocks, but not everything (I think blocks that it customises, such as swaying grass, aren't hidden), and also limits how far ore blocks can be seen down below.
[Before](https://user-images.githubusercontent.com/10192165/90130860-11e5e000-dd63-11ea-83ad-6149f4f0443b.png) / [After](https://user-images.githubusercontent.com/10192165/90130867-13afa380-dd63-11ea-945c-384723db32cf.png)

For comparison, here's that view in 'vanilla' Wurst:
[Before](https://user-images.githubusercontent.com/10192165/90131262-bff18a00-dd63-11ea-83b9-27808fa95ea5.png) / [After](https://user-images.githubusercontent.com/10192165/90131264-c1bb4d80-dd63-11ea-9e0e-dc45842dab80.png)

**Comment by holysnipz** [comment]
> x-ray not compat with optifine

it's well known issue: https://github.com/Wurst-Imperium/Wurst7/issues/74#issuecomment-612169210
and [since sp614x hate "hacked clients"](https://github.com/sp614x/optifine/issues/3482#issuecomment-593921599), there's no hope for the fix

But, for sodium, [there's slight hope that wurst will be compatible](https://old.reddit.com/r/WurstClient/comments/hqf48g/will_xwurst_be_compatible_with_sodium/fxz202h/)

**Comment by XenoTheStrange** [comment]
Xray resource packs work fine though. Can wurst use this instead of its normal, conflicting technique?
