### ISSUE TITLE
Scrolling past default GUI end causes crash

### ISSUE THREAD

**Issue by DannyZolp** [Wurst-Imperium/Wurst7#182]
## Description
When scrolling in the default GUI (by pressing "RSHIFT") too far, the game crashes

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Login to a Minecraft world or Server (works on both)
2. Press RSHIFT to enter the GUI
3. Scroll past the normal limit

## Crash Report
https://pastebin.com/nnMCk1gu

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/4/20 3:08 PM
Description: Ticking screen

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.wurstclient.navigator.NavigatorMainScreen.onUpdate(NavigatorMainScreen.java:140)
	at net.wurstclient.navigator.NavigatorScreen.method_25393(NavigatorScreen.java:133)
	at net.minecraft.class_310.method_1572(class_310.java:1501)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_310.method_1574(class_310.java:1501)
	at net.minecraft.class_310.method_1523(class_310.java:996)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.wurstclient.navigator.NavigatorMainScreen.onUpdate(NavigatorMainScreen.java:140)
	at net.wurstclient.navigator.NavigatorScreen.method_25393(NavigatorScreen.java:133)
	at net.minecraft.class_310.method_1572(class_310.java:1501)

-- Affected screen --
Details:
	Screen name: net.wurstclient.navigator.NavigatorMainScreen
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)

-- Affected level --
Details:
	All players: 23 total; [class_746['DannyZolp'/8703, l='ClientLevel', x=242.20, y=35.00, z=-54.16], class_745['BraveGamez'/8083, l='ClientLevel', x=237.19, y=35.00, z=-45.87], class_745['RudyKleKle'/8674, l='ClientLevel', x=243.56, y=35.00, z=-25.47], class_745['CHALLENGER77777'/8636, l='ClientLevel', x=238.95, y=45.50, z=-23.40], class_745['OmegaBuilder749'/8666, l='ClientLevel', x=241.69, y=35.83, z=-30.38], class_745['nbellolugo'/8686, l='ClientLevel', x=241.10, y=37.00, z=-25.57], class_745['ArkplayzYT'/7320, l='ClientLevel', x=241.21, y=35.00, z=-52.24], class_745['Antonyono'/7019, l='ClientLevel', x=241.56, y=35.00, z=-53.27], class_745['Jcross666'/7532, l='ClientLevel', x=241.99, y=35.00, z=-53.01], class_745['Generic_Matthew'/8064, l='ClientLevel', x=240.83, y=35.00, z=-53.22], class_745['Spaxeren'/8670, l='ClientLevel', x=240.50, y=35.00, z=-48.50], class_745['Skau77'/8672, l='ClientLevel', x=242.96, y=35.00, z=-51.67], class_745['SA1226'/8606, l='ClientLevel', x=241.04, y=35.00, z=-48.93], class_745['bruhenr'/8671, l='ClientLevel', x=241.49, y=35.00, z=-49.51], class_745['CobraINS'/8699, l='ClientLevel', x=242.18, y=35.00, z=-51.99], class_745['Lowie_Hooybergs'/8701, l='ClientLevel', x=243.44, y=35.00, z=-52.56], class_745['CaptainOfWorld'/8702, l='ClientLevel', x=242.65, y=35.00, z=-48.88], class_745['ExpoSolar'/8627, l='ClientLevel', x=250.50, y=35.00, z=-38.11], class_745['FFrosted'/5479, l='ClientLevel', x=243.19, y=35.00, z=-28.78], class_745['sonofcoy'/8684, l='ClientLevel', x=241.47, y=38.14, z=-21.18], class_745['TeakIvy'/7997, l='ClientLevel', x=273.43, y=35.00, z=-33.46], class_745['Flamingbow12238'/8704, l='ClientLevel', x=240.56, y=35.00, z=-54.19], class_745['SPG_gamer_slo'/8705, l='ClientLevel', x=241.96, y=35.00, z=-52.39]]
	Chunk stats: Client Chunk Cache: 729, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (241,35,-53), Chunk: (at 1,2,11 in 15,-4; contains blocks 240,0,-64 to 255,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 5368 game time, 792000 day time
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:ccdd9e3:unknown) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:674)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3382232344 bytes (3225 MB) / 5665980416 bytes (5403 MB) up to 15224799232 bytes (14519 MB)
	CPUs: 16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx16333m
	Fabric Mods: 
		fabric: Fabric API 0.20.1+build.401-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c4e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1884e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea1884e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea1884e
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e4e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa14e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced84e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea1884e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.1+build.205
		minecraft: Minecraft 1.16.2
		wurst: Wurst Client v7.5-MC1.16.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric/fabric-renderer-api-v1, fabric/fabric-screen-handler-api-v1, fabric/fabric-networking-blockentity-v0, fabric/fabric-keybindings-v0, fabric/fabricloader, fabric/fabric-tool-attribute-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-containers-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-events-interaction-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-item-api-v1, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-key-binding-api-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-resource-loader-v0, fabric/fabric-textures-v0, fabric/fabric-content-registries-v0, fabric/fabric-tag-extensions-v0, fabric/fabric-rendering-fluids-v1, fabric/fabric-registry-sync-v0, fabric/fabric-blockrenderlayer-v1, fabric/fabric-lifecycle-events-v1, fabric/fabric-mining-levels-v0, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/fabric-events-lifecycle-v0, fabric/wurst, fabric/fabric, fabric/fabric-models-v0, fabric/fabric-item-groups-v0, fabric/fabric-networking-v0, fabric/fabric-object-builders-v0
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 

```

**Comment by wurstisgood** [comment]
it crashes really

**Comment by Alexander01998** [comment]
> it crashes really

How do you get it to crash? I can't seem to "scroll past the normal limit". It just stops at the bottom as it should.

**Comment by DannyZolp** [comment]
Weird ub with my system specifically
