### ISSUE TITLE
Wurst interferes with other mods that use chat

### ISSUE THREAD

**Issue by ImmortalZypther** [Wurst-Imperium/Wurst7#207]
## Description
Something about Wurst seems to interfere with some mods that use chat. 
For example, the screenshot below shows Baritone failing to go to the next window when clicking the right arrow. 
The normal behavior would show the next help window instead of sending a message like that in chat.

Tweakaroo is also set to show chat timestamps, however they do not show up either. 

I've tested removing every mod except Wurst and it's 100% Wurst causing these compatibility issues in chat.

## Steps To Reproduce
1. Install Wurst
2. Install Fabritone (Fabric compatible version of Baritone)
3. Install Tweakaroo
4. Enable Chat Timestamps in Tweakaroo
5. Go into a world and type "#help" for Baritone's help menu

## Screenshots / Videos (Optional)
![image](https://user-images.githubusercontent.com/21045587/98453894-39630380-212c-11eb-9511-1f9982c53185.png)

## Crash Report

```

---- Minecraft Crash Report ----
// You're mean.

Time: 2020-11-07 19:03:30 EST
Description: Manually triggered client-side debug crash

java.lang.Throwable
    at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
    at net.minecraft.client.Keyboard.pollDebugCrash(Keyboard:582)
    at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1574)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:996)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.MinecraftClient.handler$zcl000$afterCrashHandled(MinecraftClient:5344)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:674)
    at net.minecraft.client.main.Main.main(Main:215)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- OptiFabric --
  OptiFine jar designed for: 1.16.3
  OptiFine jar version: OptiFine_1.16.3_HD_U_G4
  OptiFine jar status: Valid OptiFine installer
  OptiFine remapped jar: C:\Users\Masae\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.3_HD_U_G4\Optifine-mapped.jar
  OptiFabric error: <None>

-- System Details --
  Minecraft Version: 1.16.3
  Minecraft Version ID: 1.16.3
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 14.0.2, AdoptOpenJDK
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
  Memory: 1429040448 bytes (1362 MB) / 2013265920 bytes (1920 MB) up to 4294967296 bytes (4096 MB)
  CPUs: 8
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Fabric Loader (fabricloader)
  Fabric Mods: appleskin: AppleSkin 1.0.11
               authme: Auth Me 1.4.0
               autoconfig1u: Auto Config v1 Updated 3.2.2
               baritoe: Baritone 1.6.1
               blue_endless_jankson: jankson 1.2.0
               can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.0.2
               carpet: Carpet Mod in Fabric 1.4.12
               cleancut: CleanCut mc1.16-2.1-fabric
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-config2: Cloth Config v4 4.8.2
               com_github_kaptainwutax_biomeutils: BiomeUtils 590f697a2ccb6c6bdba8e2fea891a25ace75c947
               com_github_kaptainwutax_chunkrandomreversal: ChunkRandomReversal 209eefb8ed2bd097e3c55d3934ba508b664443da
               com_github_kaptainwutax_featureutils: FeatureUtils 25f73f26289a65a314cd66badc3c433d7f8c37b0
               com_github_kaptainwutax_latticg: LattiCG 38f0b3d33e15ad2e6ce9ddb1f588e2b9a8c96174
               com_github_kaptainwutax_mathutils: MathUtils 6c2d50eacad0241ff76119e6e703b70bac4b4bce
               com_github_kaptainwutax_seedutils: SeedUtils 0de70bc772fef95d8acfa6991e7278ee53a8b46c
               controlling: Controlling For Fabric 1.1.2
               dynamicfps: Dynamic FPS 1.2.1
               easiervillagertrading: EasierVillagerTrading 1.16.2-fabric0.17.2-1.5.3
               enchantedtooltips: Enchanted ToolTips 1.3.4-1.16
               fabric: Fabric API 0.25.0+build.415-1.16
               fabric-api-base: Fabric API Base 0.2.0+9f0fb4b895
               fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+8367596d95
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a95
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a95
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a95
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab95
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a95
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a95
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a95
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a95
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
               fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf3a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a95
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.4+2b46237995
               fabricloader: Fabric Loader 0.10.6+build.214
               fishelp: Fishelp 1.0.2
               horseinfo: Horse Info 0.2.2-1.16.1
               inventoryprofiles: Inventory Profiles 0.4.2
               kyrptconfig: Kytpt Config 1.1.4-1.16
               loadcatcher: Entrypoint Catcher 2.0.0
               malilib: MaLiLib 0.10.0-dev.21+arne.1
               minecraft: Minecraft 1.16.3
               minihud: MiniHUD 0.19.0-dev.20201103.184029
               mm: Manningham Mills 2.1
               modmenu: Mod Menu 1.14.6+build.31
               multiconnect: MultiConnect 1.3.29
               multiconnect-api: MultiConnect API 1.3.29
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               optifabric: OptiFabric 1.8.0
               petowner: Pet Owner 1.7.0-1.16.2+
               phosphor: Phosphor 0.6.0+build.7
               roughlyenoughitems: Roughly Enough Items 5.7.0
               roughlyenoughitems-api: REI (API) 5.7.0
               roughlyenoughitems-default-plugin: REI (Default Plugin) 5.7.0
               roughlyenoughitems-runtime: REI (Runtime) 5.7.0
               roughlyenoughresources: Roughly Enough Resources 2.1.2
               seedcracker: Seed Cracker 0.2.2-beta
               tooltipfix: ToolTip Fix 1.0.2-1.16
               tweakeroo: Tweakeroo 0.10.0-dev.20201103.184154
               waila: Hwyla 1.9.22
               wurst: Wurst Client v7.6.2-MC1.16.3
               xaerominimap: Xaero's Minimap 20.27.2
               xaeroworldmap: Xaero's World Map 1.11.0
  Launched Version: fabric-loader-0.10.6+build.214-1.16.3
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: vanilla, fabric/fabric, fabric/fabric-api-base, fabric/fabric-biome-api-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-command-api-v1, fabric/fabric-containers-v0, fabric/fabric-content-registries-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-game-rule-api-v1, fabric/fabric-item-api-v1, fabric/fabric-item-groups-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-keybindings-v0, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/fabric-mining-levels-v0, fabric/fabric-models-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-networking-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-object-builders-v0, fabric/fabric-registry-sync-v0, fabric/fabric-renderer-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-renderer-registries-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-resource-loader-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tag-extensions-v0, fabric/fabric-textures-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabricloader, file/VanillaTweaks_r647115.zip
  Current Language: English (US)
  CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Client Crashes Since Restart: 32
  Integrated Server Crashes Since Restart: 1

```

**Comment by KTibow** [comment]
Here's something I came up with for JSMacros (set trigger to RecvMessage):
```js
  let chatContent = event.text;
  let chatString = chatContent.getString();
  // Fix baritone clicks
  if (
    chatString.includes("[Baritone]") &&
    JSON.parse(chatContent.getJson()).extra
  ) {
    let fixedMessage = JSON.parse(chatContent.getJson());
    for (part of fixedMessage.extra) {
      if (part.clickEvent) {
        part.clickEvent.action = "suggest_command";
        part.clickEvent.value = part.clickEvent.value.replace(/<<\w{8}-\w{4}-\w{4}-\w{4}-\w{12}>>/, "#");
      }
      if (part.extra) {
        part.extra.forEach(part => {
          if (part.clickEvent) {
            part.clickEvent.action = "suggest_command";
            part.clickEvent.value = part.clickEvent.value.replace(/<<\w{8}-\w{4}-\w{4}-\w{4}-\w{12}>>/, "#");
          }
        });
      }
    }
    event.text.replaceFromJson(JSON.stringify(fixedMessage));
  }
```
