### ISSUE TITLE
Rendering entity in world

### ISSUE THREAD

**Issue by MarcinK50** [Wurst-Imperium/Wurst7#242]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?
Randomly when I'm use cheats from right shift or join server, game is crashes :(

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Join server
2. Use cheat from right shift menu

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 06.12.20 18:41
Description: Rendering entity in world

java.lang.NoSuchFieldError: armorModelProvider
	at net.minecraft.item.Item.fabric_getArmorModelProvider(Item:2036)
	at net.fabricmc.fabric.impl.client.rendering.ArmorRenderingRegistryImpl.getArmorModel(ArmorRenderingRegistryImpl.java:58)
	at net.fabricmc.fabric.api.client.rendering.v1.ArmorRenderingRegistry.getArmorModel(ArmorRenderingRegistry.java:115)
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.handler$zkj001$selectArmorModel(ArmorFeatureRenderer:1088)
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.getArmor(ArmorFeatureRenderer:110)
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer:36)
	at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer:22)
	at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:139)
	at net.minecraft.client.render.entity.MobEntityRenderer.render(MobEntityRenderer:43)
	at net.minecraft.client.render.entity.MobEntityRenderer.render(MobEntityRenderer:18)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:261)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1459)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1219)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1023)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:656)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1792.fabric_getArmorModelProvider(class_1792.java:2036)
	at net.fabricmc.fabric.impl.client.rendering.ArmorRenderingRegistryImpl.getArmorModel(ArmorRenderingRegistryImpl.java:58)
	at net.fabricmc.fabric.api.client.rendering.v1.ArmorRenderingRegistry.getArmorModel(ArmorRenderingRegistry.java:115)
	at net.minecraft.class_970.handler$zkj001$selectArmorModel(class_970.java:1088)
	at net.minecraft.class_970.method_4172(class_970.java:110)
	at net.minecraft.class_970.method_17157(class_970.java:36)
	at net.minecraft.class_970.method_4199(class_970.java:22)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_927.method_4072(class_927.java:43)
	at net.minecraft.class_927.method_3936(class_927.java:18)

-- Entity being rendered --
Details:
	Entity Type: minecraft:skeleton (net.minecraft.class_1613)
	Entity ID: 37025
	Entity Name: Skeleton
	Entity's Exact location: -291.73, 21.00, 524.50
	Entity's Block location: World: (-292,21,524), Chunk: (at 12,1,12 in -19,32; contains blocks -304,0,512 to -289,255,527), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Entity's Momentum: 0.00, -0.06, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_946@7845202b
	Location: 15.57,-25.62,-28.80 - World: (15,-26,-29), Chunk: (at 15,-2,3 in 0,-2; contains blocks 0,0,-32 to 15,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: -90.0
	Delta: 0.76
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.method_22710(class_761.java:1219)
	at net.minecraft.class_757.method_3188(class_757.java:727)

-- Affected level --
Details:
	All players: 1 total; [class_746['Marcinmk'/37005, l='ClientLevel', x=-307.30, y=45.00, z=553.30]]
	Chunk stats: SodiumChunkCache: 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,78,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 78311 game time, 611359723 day time
	Server brand: Waterfall <- Concrete
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:674)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 432168952 bytes (412 MB) / 1241513984 bytes (1184 MB) up to 3204448256 bytes (3056 MB)
	CPUs: 8
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx3045m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		crowdin-translate: CrowdinTranslate 1.2
		customportalapi: customportalapi 0.0.1-beta7-1.16
		fabric: Fabric API 0.27.1+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+6a2618f53a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+6a2618f53a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+6a2618f53a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.1+285766753a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		geckolib3: Geckolib 3.0.0-beta.5
		io_sentry_sentry: sentry 3.1.0
		jankson: Jankson 3.0.1+j1.2.0
		libgui: LibGui 3.2.2+1.16.3
		minecraft: Minecraft 1.16.3
		modmenu: Mod Menu 1.14.6+build.31
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		sodium: Sodium 0.1.0
		the_aether: The Aether 1.16.4-v.1.0.0
		wurst: Wurst Client v7.8-MC1.16.3
	Launched Version: fabric-loader-0.10.8-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13587 Compatibility Profile Context 19.40.54.07 26.20.14054.7003, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 
```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by MarcinK50** [comment]
This is VERY randomly, beacuse when i moved the mouse, game crashes

**Comment by MarcinK50** [comment]
bruh
