### ISSUE TITLE
Randome crush (using WSpammer) (Wurst 1.12 OF)

### ISSUE THREAD

**Issue by Yoticc** [Wurst-Imperium/Wurst7#244]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. I open WSpammer
2. Write in WSpammer 
"
.goto ~ ~ ~-60
.goto ~ ~ ~-60
.goto ~ ~ ~-60
.goto ~ ~ ~60
.goto ~ ~ ~60
.goto ~ ~ ~60

"
3. 

## Screenshots / Videos (Optional)
![image](https://user-images.githubusercontent.com/55879406/101353664-020b8200-38a5-11eb-9721-b89ee85da2fb.png)

## Crash Report
```
---- Wurst Client Crash Report ----
// Why did you do that?

Time: 12/7/20 3:55 PM
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
	at net.wurstclient.features.commands.GoToCmd.onRender(GoToCmd.java:114)
	at net.wurstclient.events.RenderListener$RenderEvent.fire(RenderListener.java:32)
	at net.wurstclient.event.EventManager.fire(EventManager.java:49)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:2168)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1767)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1517)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1272)
	at net.minecraft.client.Minecraft.run(Minecraft.java:446)
	at net.minecraft.client.main.Main.main(Main.java:161)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.wurstclient.features.commands.GoToCmd.onRender(GoToCmd.java:114)
	at net.wurstclient.events.RenderListener$RenderEvent.fire(RenderListener.java:32)

-- Affected event --
Details:
	Event class: net.wurstclient.events.RenderListener$RenderEvent
Stacktrace:
	at net.wurstclient.event.EventManager.fire(EventManager.java:49)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:2168)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1767)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['zYotic'/13958, l='MpServer', x=-255166.50, y=5.00, z=86912.60]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 97733 game time, 2362934382 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 3 total; [EntityPlayerSP['zYotic'/13958, l='MpServer', x=-255166.50, y=5.00, z=86912.60], EntityItem['item.tile.hellrock'/19421628, l='MpServer', x=-255166.13, y=5.00, z=86901.74], EntityItem['item.tile.hellrock'/19420365, l='MpServer', x=-255166.88, y=5.00, z=86934.43]]
	Retry entities: 0 total; []
	Server brand: Waterfall <- 2b2t
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:561)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:3260)
	at net.minecraft.client.Minecraft.run(Minecraft.java:463)
	at net.minecraft.client.main.Main.main(Main.java:161)

-- System Details --
Details:
	Minecraft Version: 1.12
	Wurst Client Version: 6.34.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1313789712 bytes (1252 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Wurst MC 1.12 OF
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5700 Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: resour-pack by Yotic (incompatible)
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Xeon(R) CPU E5462 @ 2.80GHz
```

**Comment by TheAwesome98-Real** [comment]
wrong repo
