### ISSUE TITLE
cant "build"

### ISSUE THREAD

**Issue by KeparYTbcc** [Wurst-Imperium/Wurst7#305]
C:\Users\my-pc2\Desktop\DeV\SECRET!\Wurst7>gradlew.bat ecplipse
Exception in thread "main" java.lang.RuntimeException: Could not determine wrapper version.
        at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:111)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: No build receipt resource found.
        at org.gradle.wrapper.GradleWrapperMain.wrapperVersion(GradleWrapperMain.java:97)

**Comment by Alexander01998** [comment]
Gradle doesn't support paths with the `!` character in them. See https://github.com/MinecraftForge/ForgeGradle/issues/227

**Comment by KeparYTbcc** [comment]
im not sure wdym, so how i do now?, i want to bas on youy source code, to make my own client, for me and my friends

**Comment by AndrewBruhMoment** [comment]
This is the path to where your client is located.
C:\Users\my-pc2\Desktop\DeV\SECRET!\Wurst7
In your path, you have an "!" (...\DeV\SECRET**_!_**\Wurst7>...)
Gradlew does not support your path that is above because it has an exclamation point in it. Make a new path that has no "!"
