### ISSUE TITLE
Wurst crashes entire game client when placing modded block

### ISSUE THREAD

**Issue by TheAwesome98-Real** [Wurst-Imperium/Wurst7#307]
Any block from the mod True Secret Rooms (haven't tested others) crashes the game (I know it's wurst since the crash report mentions it). If you'd like any more info, please let me know.

**Comment by faseri** [comment]
Is that hard for you to open an issue properly? Description, steps to reproduce, crash report...

**Comment by TheAwesome98-Real** [comment]
it happens with furnaces too apparently.

**Comment by TheAwesome98-Real** [comment]
> Is that hard for you to open an issue properly? Description, steps to reproduce, crash report...

1. place block
2. crash game

**Comment by TheAwesome98-Real** [comment]
[crash-2021-02-10_15.04.29-client.txt](https://github.com/Wurst-Imperium/Wurst7/files/5959001/crash-2021-02-10_15.04.29-client.txt)
this

**Comment by Alexander01998** [comment]
> [crash-2021-02-10_15.04.29-client.txt](https://github.com/Wurst-Imperium/Wurst7/files/5959001/crash-2021-02-10_15.04.29-client.txt)
> this

```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 10/02/2021, 15:04
Description: Firing Wurst event

java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/networking/CustomPayloadC2SPacketAccessor
	at net.wurstclient.other_features.VanillaSpoofOtf.onSentConnectionPacket(VanillaSpoofOtf.java:48)
	at net.wurstclient.events.ConnectionPacketOutputListener$ConnectionPacketOutputEvent.fire(ConnectionPacketOutputListener.java:56)
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_2535.localvar$zbo000$onSendPacket(class_2535.java:554)
	at net.minecraft.class_2535.method_10752(class_2535.java)
	at net.minecraft.class_2535.method_10743(class_2535.java:165)
	at mcp.mobius.waila.network.NetworkHandler.requestTile(NetworkHandler.java:109)
	at mcp.mobius.waila.api.impl.MetaDataProvider.gatherBlockComponents(MetaDataProvider.java:36)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:91)
	at net.minecraft.class_310.handler$zkf000$clientTick(class_310.java:6362)
	at net.minecraft.class_310.method_1574(class_310.java:1496)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.wurstclient.other_features.VanillaSpoofOtf.onSentConnectionPacket(VanillaSpoofOtf.java:48)
	at net.wurstclient.events.ConnectionPacketOutputListener$ConnectionPacketOutputEvent.fire(ConnectionPacketOutputListener.java:56)

-- Affected event --
Details:
	Event class: net.wurstclient.events.ConnectionPacketOutputListener$ConnectionPacketOutputEvent
Stacktrace:
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_2535.localvar$zbo000$onSendPacket(class_2535.java:554)
	at net.minecraft.class_2535.method_10752(class_2535.java)
	at net.minecraft.class_2535.method_10743(class_2535.java:165)
	at mcp.mobius.waila.network.NetworkHandler.requestTile(NetworkHandler.java:109)
	at mcp.mobius.waila.api.impl.MetaDataProvider.gatherBlockComponents(MetaDataProvider.java:36)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:91)
	at net.minecraft.class_310.handler$zkf000$clientTick(class_310.java:6362)

-- Affected level --
Details:
	All players: 1 total; [class_746['dolphinLMAO'/128, l='ClientLevel', x=-505.31, y=92.00, z=-38.33]]
	Chunk stats: Client Chunk Cache: 1369, 1024
	Level dimension: minecraft:overworld
	Level spawn location: World: (23,78,15), Chunk: (at 7,4,15 in 1,0; contains blocks 16,0,0 to 31,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 46757 game time, 7940 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 5.8.0-41-generic
	Java Version: 11.0.10, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 447561976 bytes (426 MB) / 1409286144 bytes (1344 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecs: Amecs 1.3.3+mc.1.16.3
		amecsapi: Amecs API 1.1.3+mc1.16.5
		bitsandchisels: BitsAndChisels 2.0.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v2 4.4.0-unstable
		fabric: Fabric API 0.29.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.1+cbe9176f3a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.2+8004b36d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.5+cbe9176f3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.2+cbe9176f3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.2.0+cbe9176f3a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+2a4333d33a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: Fabric Particles (v1) 0.2.3+cbe9176f3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.3+be155ae23a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.0+cbe9176f3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.0+c26373133a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.1+0d4d7e343a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.3+cbe9176f3a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		lambdacontrols: LambdaControls 1.5.0+1.16.2
		minecraft: Minecraft 1.16.4
		modmenu: Mod Menu 1.14.13+build.19
		offlineskins: OfflineSkins 1.16.4-v1-fabric
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		spruceui: SpruceUI 1.6.4
		stacc: Stacc 1.0.1
		truerooms: True Secret Rooms 1.1.2-hotfix
		waila: Hwyla 1.9.22
		wurst: Wurst Client v7.11-MC1.16.4
		xlpackets: XLPackets 1.1
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series (POLARIS10, DRM 3.38.0, 5.8.0-41-generic, LLVM 11.0.0) GL version 4.6 (Compatibility Profile) Mesa 20.2.6, X.Org
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor
```

**Comment by Alexander01998** [comment]
> java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/networking/CustomPayloadC2SPacketAccessor
> 	at net.wurstclient.other_features.VanillaSpoofOtf.onSentConnectionPacket(VanillaSpoofOtf.java:48)

You are using VanillaSpoof on a modded server. With VanillaSpoof active, the server thinks you are using vanilla. That's why it's not working. You need to turn off VanillaSpoof to play on modded servers.

**Comment by TheAwesome98-Real** [comment]
whoops i forgot to turn it off lmao
