### ISSUE TITLE
.dupe crashes my instance instead of kicking me from the server (like in tutorials)

### ISSUE THREAD

**Issue by Z2Up1UwcaYOyZq** [Wurst-Imperium/Wurst7#350]
## Description
Title.
I'm using Crystal Launcher on Linux
Server and instance version is 1.16.3
Before crashing, client shows "saving world" message, even when using a third-party server 

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. write .dupe while holding Book & Quill (works even in singleplayer)

## Crash Report

```

---- Minecraft Crash Report ----
// There are four lights!

Time: 3/25/21, 2:33 PM
Description: Running Wurst command

java.lang.NoSuchMethodError: 'void net.minecraft.class_2820.<init>(net.minecraft.class_1799, boolean, int)'
  at net.wurstclient.commands.DupeCmd.call(DupeCmd.java:65)
  at net.wurstclient.command.CmdProcessor.runCmd(CmdProcessor.java:83)
  at net.wurstclient.command.CmdProcessor.process(CmdProcessor.java:57)
  at net.wurstclient.command.CmdProcessor.onSentMessage(CmdProcessor.java:40)
  at net.wurstclient.events.ChatOutputListener$ChatOutputEvent.fire(ChatOutputListener.java:57)
  at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
  at net.wurstclient.event.EventManager.fire(EventManager.java:42)
  at net.minecraft.class_746.handler$zeg000$onSendChatMessage(class_746.java:1280)
  at net.minecraft.class_746.method_3142(class_746.java)
  at net.minecraft.class_437.method_25425(class_437.java:313)
  at net.minecraft.class_437.method_25427(class_437.java:306)
  at net.minecraft.class_408.method_25404(class_408.java:98)
  at net.minecraft.class_309.method_1454(class_309.java:345)
  at net.minecraft.class_437.method_25412(class_437.java:435)
  at net.minecraft.class_309.method_1466(class_309.java:343)
  at net.minecraft.class_309.method_22678(class_309.java:433)
  at net.minecraft.class_1255.execute(class_1255.java:94)
  at net.minecraft.class_309.method_22676(class_309.java:433)
  at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
  at org.lwjgl.system.JNI.invokeV(Native Method)
  at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
  at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
  at net.minecraft.class_1041.method_15998(class_1041.java:308)
  at net.minecraft.class_310.method_1523(class_310.java:1043)
  at net.minecraft.class_310.method_1514(class_310.java:656)
  at net.minecraft.client.main.Main.main(Main.java:215)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
  at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
  at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
  at net.wurstclient.commands.DupeCmd.call(DupeCmd.java:65)

-- Affected command --
Details:
  Command input: dupe
Stacktrace:
  at net.wurstclient.command.CmdProcessor.runCmd(CmdProcessor.java:83)
  at net.wurstclient.command.CmdProcessor.process(CmdProcessor.java:57)
  at net.wurstclient.command.CmdProcessor.onSentMessage(CmdProcessor.java:40)
  at net.wurstclient.events.ChatOutputListener$ChatOutputEvent.fire(ChatOutputListener.java:57)

-- Affected event --
Details:
  Event class: net.wurstclient.events.ChatOutputListener$ChatOutputEvent
Stacktrace:
  at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
  at net.wurstclient.event.EventManager.fire(EventManager.java:42)
  at net.minecraft.class_746.handler$zeg000$onSendChatMessage(class_746.java:1280)
  at net.minecraft.class_746.method_3142(class_746.java)
  at net.minecraft.class_437.method_25425(class_437.java:313)
  at net.minecraft.class_437.method_25427(class_437.java:306)
  at net.minecraft.class_408.method_25404(class_408.java:98)
  at net.minecraft.class_309.method_1454(class_309.java:345)

-- Affected screen --
Details:
  Screen name: net.minecraft.class_408
Stacktrace:
  at net.minecraft.class_437.method_25412(class_437.java:435)
  at net.minecraft.class_309.method_1466(class_309.java:343)
  at net.minecraft.class_309.method_22678(class_309.java:433)
  at net.minecraft.class_1255.execute(class_1255.java:94)
  at net.minecraft.class_309.method_22676(class_309.java:433)
  at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
  at org.lwjgl.system.JNI.invokeV(Native Method)
  at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
  at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)

-- Affected level --
Details:
  All players: 1 total; [class_746['playername'/86796, l='ClientLevel', x=-1431.39, y=68.00, z=-812.44]]
  Chunk stats: Client Chunk Cache: 729, 441
  Level dimension: minecraft:overworld
  Level spawn location: World: (-144,66,-256), Chunk: (at 0,4,0 in -9,-16; contains blocks -144,0,-256 to -129,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
  Level time: 113647051 game time, 114716306 day time
  Server brand: fabric
  Server type: Non-integrated multiplayer server
Stacktrace:
  at net.minecraft.class_638.method_8538(class_638.java:449)
  at net.minecraft.class_310.method_1587(class_310.java:2183)
  at net.minecraft.class_310.method_1514(class_310.java:674)
  at net.minecraft.client.main.Main.main(Main.java:215)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
  at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
  at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
  Minecraft Version: 1.16.3
  Minecraft Version ID: 1.16.3
  Operating System: Linux (amd64) version 5.11.8-artix1-1
  Java Version: 15.0.2, N/A
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 758531312 bytes (723 MB) / 1442840576 bytes (1376 MB) up to 2650800128 bytes (2528 MB)
  CPUs: 4
  JVM Flags: 9 total; -Xmx2500M -Xms800M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Fabric Mods: 
    fabric: Fabric API 0.31.0+1.16
    fabric-api-base: Fabric API Base 0.2.1+9354966b7d
    fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
    fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
    fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
    fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
    fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
    fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
    fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
    fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
    fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
    fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
    fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
    fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
    fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
    fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
    fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
    fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
    fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
    fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
    fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
    fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
    fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
    fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
    fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
    fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
    fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
    fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
    fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
    fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
    fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
    fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
    fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
    fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
    fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
    fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
    fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
    fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
    fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
    fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
    fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
    fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
    fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
    fabricloader: Fabric Loader 0.11.2
    java: OpenJDK 64-Bit Server VM 15
    minecraft: Minecraft 1.16.3
    wurst: Wurst Client v7.14-MC1.16.5
  Launched Version: 1.16.3
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: AMD VERDE (DRM 2.50.0, 5.11.8-artix1-1, LLVM 11.1.0) GL version 4.5 (Compatibility Profile) Mesa 20.3.4, AMD
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fast
  Resource Packs: Fabric Mods
  Current Language: English (US)
  CPU: 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
#@!@# Game crashed! Crash report saved to: #@!@# wurst_1.16.3/.minecraft/crash-reports/crash-2021-03-25_14.33.48-client.txt

[2021-03-25-1.log.gz](https://github.com/Wurst-Imperium/Wurst7/files/6205123/2021-03-25-1.log.gz)

```

**Comment by Z2Up1UwcaYOyZq** [comment]
https://github.com/Wurst-Imperium/Wurst7/files/6205123/2021-03-25-1.log.gz

**Comment by Z2Up1UwcaYOyZq** [comment]
Apparently this dupe works only in 1.16.4 and 1.16.5 (haven't tested in 1.17).
Closing this issue.

**Comment by Alexander01998** [comment]
This happened because you used a Wurst MC1.16.5 release in Minecraft 1.16.3. Using a slightly different Minecraft version than intended is usually fine, but in this case the specific piece of code that makes .dupe work is different in Minecraft 1.16.3 vs 1.16.4+.

This is why the game appeared to be working just fine, but then it crashed when you were running .dupe.

I have released a separate [Wurst MC1.16.3 version](https://www.wurstclient.net/download/minecraft-1-16-3/) that can duplicate items on Minecraft 1.16.3 servers. Be warned, however, that using this version in 1.16.4+ servers will cause a similar crash.
