### ISSUE TITLE
AutoTool not counting hoe as a tool

### ISSUE THREAD

**Issue by Signko** [Wurst-Imperium/Wurst7#371]
## Description
I wouldn't describe it as a bug, more like an imperfection. When I am farming and having AutoTool on, it chooses any other item in the inventory other than the netherite hoe with fortune 1 (which if you didn't know multiplies the number of seeds you're getting from farming)
## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Make AutoTool count hoe as a tool for crops like wheat, carrot etc.

## Crash Report

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 14.04.21 19:54
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.class_309.method_1474(class_309.java:475)
	at net.minecraft.class_310.method_1574(class_310.java:1668)
	at net.minecraft.class_310.method_1523(class_310.java:1042)
	at net.minecraft.class_310.method_1514(class_310.java:700)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_309.method_1474(class_309.java:475)

-- Affected level --
Details:
	All players: 1 total; [class_746['myname'/35116, l='ClientLevel', x=335.84, y=63.94, z=-39.29]]
	Chunk stats: 289, 160
	Level dimension: minecraft:overworld
	Level spawn location: World: (208,65,120), Section: (at 0,1,8 in 13,4,7; chunk contains blocks 208,-64,112 to 223,319,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2103056 game time, 3016701 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2259)
	at net.minecraft.class_310.method_1514(class_310.java:719)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 21w14a
	Minecraft Version ID: 21w14a
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 254844488 bytes (243 MB) / 711188480 bytes (678 MB) up to 2566127616 bytes (2447 MB)
	CPUs: 2
	JVM Flags: 5 total; -Xmn128M -Xmx2459M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC
	Fabric Mods: 
		fabric: Fabric API 0.32.7+1.17
		fabric-api-base: Fabric API Base 0.2.2+23b3c92e17
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.2+413ddf6417
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.8+413ddf6417
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+92519afa17
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+bb68760017
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa17
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+41a6855217
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+23b3c92e17
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+92519afa17
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.9+413ddf6417
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+92519afa17
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+d748de6c17
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+92519afa17
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+23b3c92e17
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.6+23b3c92e17
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+524a2e8517
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e17
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+23b3c92e17
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+92519afa17
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa17
		fabric-models-v0: Fabric Models (v0) 0.2.1+92519afa17
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.7+413ddf6417
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+413ddf6417
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa17
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.5+40e100eb17
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+92519afa17
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+92519afa17
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.8+413ddf6417
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+92519afa17
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+413ddf6417
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.1.0+2a1dabb617
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+92519afa17
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+92519afa17
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa17
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.2+41a6855217
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.5+23b3c92e17
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+41a6855217
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+23b3c92e17
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.8+23b3c92e17
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.3+41a6855217
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+92519afa17
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.9+36b77c3e17
		fabricloader: Fabric Loader 0.11.3
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.17-alpha.21.14.a
		wurst: Wurst Client v7.14-MC21w14a
	Launched Version: fabric-loader-0.11.3-21w14a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics GL version 3.2.0 - Build 20.19.15.5171, Intel
	GL Caps: Using framebuffer using OpenGL 3.2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: Русский (Россия)
	CPU: 2x Intel(R) Celeron(R) CPU G1840 @ 2.80GHz
```

**Comment by AndrewBruhMoment** [comment]
AutoTool doesn't work with fortune, and because a hoe wouldn't break crops faster, it does not swap to the hoe. To fix this, a general new feature would have to be implemented into AutoTool that would swap to a tool with the highest fortune level for items such as ores, crops, and other things that can be affected by fortune. This feature could also swap back to a tool without fortune for blocks without a need for it, but at this point, I'm just getting picky.
