### ISSUE TITLE
Crashing issues with a few features

### ISSUE THREAD

**Issue by Hyp3r10** [Wurst-Imperium/Wurst7#391]
_I cant tell if there are certain things disabled or if it's broken._

**SEARCH** **_(ESP)_**

- Cannot enter / search for any blocks, the entering it in and being able to pull up the ID works.
- Cannot view what I'm searching for.
- Upon using The game Crashes. I've reinstalled it multiple times to see if I installed it wrong, the result remained the same.

**TUNNELER**

- CRASHES the game if you use it.

_**Can you guys test the wurst client to see if its just me or you. first thing to try is search. These two has been broken since 21w11a .**_

**Comment by faseri** [comment]
Please add crash-report file

**Comment by Hyp3r10** [comment]
> Please add crash-report file

For some reason Its invisible. I Have hooked it up right following the steps. I made sure by uninstalling and reinstalling Fabric and wurst. The crash reports are hidden on my pc for some reason.

**Comment by AndrewBruhMoment** [comment]
I believe each crash report is saved in the `Logs` folder of your `.minecraft` or another folder. Try holding f3 + c to manually crash the game and see if the report is saved.

**Comment by Hyp3r10** [comment]
[latest.log](https://github.com/Wurst-Imperium/Wurst7/files/6416422/latest.log)
_This is my latest log. With searches odd crashing_

> I believe each crash report is saved in the `Logs` folder of your `.minecraft` or another folder. Try holding f3 + c to manually crash the game and see if the report is saved.

**Comment by GreenScripter** [comment]
If I run tunneller in a development environment, I can see this error, however said error does not get written to the log. I also tested with both java 8 and java 14, with pretty much the same crash in both cases.

FATAL ERROR in native method: Thread[Render thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
        at org.lwjgl.opengl.GL11.glGenLists(Native Method)
        at net.wurstclient.hacks.TunnellerHack.onEnable(TunnellerHack.java:130)
        at net.wurstclient.hack.Hack.setEnabled(Hack.java:83)
        at net.wurstclient.hack.Hack.doPrimaryAction(Hack.java:100)
        at net.wurstclient.navigator.NavigatorMainScreen.leftClick(NavigatorMainScreen.java:185)
        at net.wurstclient.navigator.NavigatorMainScreen.onMouseClick(NavigatorMainScreen.java:135)
        at net.wurstclient.navigator.NavigatorScreen.mouseClicked(NavigatorScreen.java:66)
        at net.minecraft.client.Mouse.method_1611(Mouse.java:92)
        at net.minecraft.client.Mouse$$Lambda$4329/0x00000008016b2c40.run(Unknown Source)
        at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
        at net.minecraft.client.Mouse.onMouseButton(Mouse.java:92)
        at net.minecraft.client.Mouse.method_22686(Mouse.java:162)
        at net.minecraft.client.Mouse$$Lambda$4328/0x00000008016b3840.run(Unknown Source)
        at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102)
        at net.minecraft.client.Mouse.method_22684(Mouse.java:162)
        at net.minecraft.client.Mouse$$Lambda$3415/0x00000008014e9440.invoke(Unknown Source)
        at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
        at org.lwjgl.system.JNI.invokeV(Native Method)
        at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050)
        at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)
        at net.minecraft.client.util.Window.swapBuffers(Window.java:309)
        at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1099)
        at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:701)
        at net.minecraft.client.main.Main.main(Main.java:217)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@14.0.1/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@14.0.1/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@14.0.1/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@14.0.1/Method.java:564)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
        at java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(java.base@14.0.1/DirectMethodHandle$Holder)
        at java.lang.invoke.LambdaForm$MH/0x0000000800b79840.invokeExact_MT(java.base@14.0.1/LambdaForm$MH)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

**Comment by Hyp3r10** [comment]
> also tested with both java 8 and java 14, with pretty much the same crash in both cases.

Same log as you when I run tunneler and Search. Except im think they both have an issue with rendering.
