### ISSUE TITLE
Mod 'Wurst Client' (wurst) requires version 0.12.1 or later of mod fabric, which is missing!

### ISSUE THREAD

**Issue by ChillerDragon** [Wurst-Imperium/Wurst7#401]
## Description
Crash on MultiMC launch
Mod 'Wurst Client' (wurst) requires version 0.12.1 or later of mod fabric, which is missing!

I know it sounds more like an setup or MultiMC issue. Also it used to work at some point and i checkout out the old commits that worked previously but could not get them running again. I do not really use any other mods so I struggeld a bit with testing my MultiMC. I installed [Sodium](https://github.com/CaffeineMC/sodium-fabric) that did not seem to have any issues. So is anyone here using linux and MultiMC and can reproduce it? Any ideas on whats going on here?

## Steps To Reproduce
1. build Wurst7 from source on debian or arch linux
2. slap it into MultiMC5
3. launch and crash

## Crash Report

MultiMC launch log

```
MultiMC version: 0.6.12-custom


Minecraft folder is:
/home/chiller/.local/share/multimc/instances/lgl/.minecraft


Java path is:
/usr/lib/jvm/java-8-openjdk/jre/bin/java


Checking Java version...
Java is version 1.8.0_292, using 64-bit architecture, from Oracle Corporation.


Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

Subsystem: Gigabyte Technology Co., Ltd Device d000

Kernel driver in use: i915

NVIDIA Corporation GM204 [GeForce GTX 980] (rev a1)

Subsystem: NVIDIA Corporation Device 1116

Kernel driver in use: nvidia

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  /home/chiller/.local/share/multimc/instances/lgl/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /home/chiller/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/chiller/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/chiller/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/chiller/.local/share/multimc/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /home/chiller/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/chiller/.local/share/multimc/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /home/chiller/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/chiller/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/chiller/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /home/chiller/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/chiller/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/chiller/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /home/chiller/.local/share/multimc/libraries/net/fabricmc/intermediary/1.16.5/intermediary-1.16.5.jar
  /home/chiller/.local/share/multimc/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  /home/chiller/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar
  /home/chiller/.local/share/multimc/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  /home/chiller/.local/share/multimc/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  /home/chiller/.local/share/multimc/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  /home/chiller/.local/share/multimc/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  /home/chiller/.local/share/multimc/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  /home/chiller/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  /home/chiller/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  /home/chiller/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  /home/chiller/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  /home/chiller/.local/share/multimc/libraries/net/fabricmc/fabric-loader/0.11.3/fabric-loader-0.11.3.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar

Mods:
  [❌] sodium-fabric-mc1.16.5-0.1.1+rev.9fbf07a.jar (disabled)
  [❌] update.sh (disabled)
  [✔️] Wurst-Client-v7.9-MC1.16.4

Params:
  --username  --version MultiMC5 --gameDir /home/chiller/.local/share/multimc/instances/lgl/.minecraft --assetsDir /home/chiller/.local/share/multimc/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 8476


Using onesix launcher.

[10:00:45] [main/INFO]: Loading for game Minecraft 1.16.5
[10:00:46] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod 'Wurst Client' (wurst) requires version 0.12.1 or later of mod fabric, which is missing!
	 - You must install version 0.12.1 or later of fabric.
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:322) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Process exited with code 1.
```

**Comment by faseri** [comment]
As stated in crash log, you use fabric 0.11.3 so you should update it at least up to 0.12.1
It's definitely not missing because latest version for 1.16.5 is 0.34.2 and you can get it on couseforge

**Comment by ChillerDragon** [comment]
Weird to that it used to work and now it seems to have updated the version requirement. I wonder what caused that. I also wonder why my MultiMC5 0.6.12 still has no later version than fabric 0.11.3

![image](https://user-images.githubusercontent.com/20344300/118306336-97144600-b4e9-11eb-966d-767d4651bef7.png)

But I guess then its obviously a MultiMC launcher issue and not a Wurst issue. Closing this issue here then thanks for the quick response @faseri

**Comment by ChillerDragon** [comment]
Oh ok I actually solved it. I am still running fabric 0.11.3 but I installed an additional mod. The [fabric api](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all) I can not remember having done it the last time but it seems to be important and fixes it now :)
