### ISSUE TITLE
wurst crashes when enabling tabgui in 1.17

### ISSUE THREAD

**Issue by feliscatusmeows** [Wurst-Imperium/Wurst7#416]
## Description
The game crashes when you enable tab gui in 1.17, and you become unable to join any servers/worlds without crashing

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. enable tabgui in 1.17
2. enjoy crash

## Crash Report
<details>

```
MultiMC version: 0.6.12-1438


Minecraft folder is:
/home/feliscatusmeows/.local/share/multimc/instances/wurst 1.161/.minecraft


Java path is:
/usr/lib/jvm/java-16-openjdk-amd64/bin/java


Checking Java version...
Java is version 16.0.1, using 64-bit architecture, from Private Build.


Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
Intel Corporation UHD Graphics (rev 05)

DeviceName: Onboard - Video

Subsystem: Micro-Star International Co., Ltd. [MSI] Device 12a7

NVIDIA Corporation Device 2192 (rev a1)

Subsystem: Micro-Star International Co., Ltd. [MSI] Device 12a7

Kernel driver in use: nvidia

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.0.0

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  /home/feliscatusmeows/.local/share/multimc/instances/wurst 1.161/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/github/oshi/oshi-core/5.7.4/oshi-core-5.7.4.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/net/fabricmc/intermediary/1.17/intermediary-1.17.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/net/fabricmc/fabric-loader/0.11.3/fabric-loader-0.11.3.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/mojang/minecraft/1.17/minecraft-1.17-client.jar

Native libraries:
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-linux.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-linux.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-linux.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-linux.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-linux.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-linux.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-linux.jar
  /home/feliscatusmeows/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-linux.jar

Mods:
  [✔️] fabric-api-0.34.9+1.17 (1)
  [❌] lazydfu-0.1.2 (3).jar (disabled)
  [✔️] Wurst-Client-v7.15.2-MC1.17

Params:
  --username  --version MultiMC5 --gameDir /home/feliscatusmeows/.local/share/multimc/instances/wurst 1.161/.minecraft --assetsDir /home/feliscatusmeows/.local/share/multimc/assets --assetIndex 1.17 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms2048m, -Xmx4096m, -Duser.language=en]


Wrapper command is:
sh -c "export __NV_PRIME_RENDER_OFFLOAD=1;export __GLX_VENDOR_LIBRARY_NAME=nvidia;exec $INST_JAVA \"$@\""


Minecraft process ID: 171786


Using onesix launcher.

[19:35:18] [main/INFO]: Loading for game Minecraft 1.17
[19:35:19] [main/INFO]: [FabricLoader] Loading 48 mods: fabric-networking-blockentity-v0@0.2.11+a02b4463d5, fabric-screen-handler-api-v1@1.1.8+a02b4463d5, minecraft@1.17, fabric-renderer-api-v1@0.4.2+a02b4463d5, fabric-keybindings-v0@0.2.2+36b77c3ed5, fabric-command-api-v1@1.1.1+a02b4463d5, fabricloader@0.11.3, fabric-screen-api-v1@1.0.3+b7ab6121d5, fabric-tool-attribute-api-v1@1.2.12+b7ab6121d5, fabric-renderer-indigo@0.4.8+a02b4463d5, fabric-structure-api-v1@1.1.10+be9da310d5, fabric-containers-v0@0.1.12+a02b4463d5, fabric-dimensions-v1@2.0.10+a02b4463d5, fabric-object-builder-api-v1@1.10.9+b7ab6121d5, java@16, fabric-crash-report-info-v1@0.1.5+be9da310d5, fabric-events-interaction-v0@0.4.8+a02b4463d5, fabric-item-api-v1@1.2.4+a02b4463d5, fabric-game-rule-api-v1@1.0.6+a02b4463d5, fabric-entity-events-v1@1.1.0+a02b4463d5, fabric-api-base@0.3.0+a02b4463d5, fabric-rendering-v0@1.1.2+92519afad5, fabric-key-binding-api-v1@1.0.4+a02b4463d5, fabric-rendering-v1@1.6.0+a02b4463d5, fabric-rendering-data-attachment-v1@0.1.5+a02b4463d5, fabric-resource-loader-v0@0.4.7+b7ab6121d5, fabric-textures-v0@1.0.6+a02b4463d5, fabric-content-registries-v0@0.2.2+a02b4463d5, fabric-tag-extensions-v0@1.1.4+a02b4463d5, fabric-biome-api-v1@3.1.11+9e521e13d5, fabric-rendering-fluids-v1@0.1.13+a02b4463d5, fabric-commands-v0@0.2.2+92519afad5, fabric-registry-sync-v0@0.7.9+a02b4463d5, fabric-blockrenderlayer-v1@1.1.5+a02b4463d5, fabric-lifecycle-events-v1@1.4.4+a02b4463d5, fabric-mining-levels-v0@0.1.3+92519afad5, fabric-renderer-registries-v1@3.2.0+a02b4463d5, fabric-networking-api-v1@1.0.11+b7ab6121d5, fabric-events-lifecycle-v0@0.2.1+92519afad5, fabric-loot-tables-v1@1.0.4+a02b4463d5, wurst@v7.15.2-MC1.17, fabric@0.34.9+1.17, fabric-item-groups-v0@0.2.10+b7ab6121d5, fabric-models-v0@0.3.0+a02b4463d5, fabric-particles-v1@0.2.4+a02b4463d5, fabric-object-builders-v0@0.7.3+a02b4463d5, fabric-networking-v0@0.3.2+92519afad5, fabric-api-lookup-api-v1@1.0.2+a02b4463d5
[19:35:19] [main/WARN]: Mod `wurst` (v7.15.2-MC1.17) does not respect SemVer - comparison support is limited.
[19:35:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/feliscatusmeows/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[19:35:20] [main/WARN]: The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
[19:35:20] [main/INFO]: Compatibility level set to JAVA_16
[19:35:21] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[19:35:32] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:35:33] [Render thread/INFO]: Setting user: feliscatusmeows
[19:35:33] [Render thread/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zzn000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[19:35:34] [Render thread/INFO]: [STDOUT]: Starting Wurst Client...
[19:35:36] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[19:35:37] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[19:35:41] [Render thread/INFO]: Narrator library successfully loaded
[19:35:42] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Renderer API (v1), Fabric Key Bindings (v0), Fabric Command API (v1), Fabric Loader, Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Structure API (v1), Fabric Containers (v0), Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Crash Report Info (v1), Fabric Events Interaction (v0), Fabric Item API (v1), Fabric Game Rule API (v1), Fabric Entity Events (v1), Fabric API Base, Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Fabric Textures (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Rendering Fluids (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Mining Levels (v0), Fabric Renderer Registries (v1), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Loot Tables (v1), Wurst Client, Fabric API, Fabric Item Groups (v0), Fabric Models (v0), Fabric Particles (v1), Fabric Object Builders (v0), Fabric Networking (v0), Fabric API Lookup API (v1))
[19:36:00] [Render thread/INFO]: OpenAL initialized.
[19:36:00] [Render thread/INFO]: Sound engine started
[19:36:02] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[19:36:02] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:36:02] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:36:02] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:36:02] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:36:02] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:36:02] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:36:06] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[19:36:06] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:36:06] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:36:52] [Render thread/INFO]: Connecting to localhost, 25565
[19:36:54] [Netty Epoll Client IO #0/INFO]: Applied 0 biome modifications to 0 of 81 new biomes in 4.401 ms
[19:36:55] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:36:55] [Render thread/ERROR]: Write access detected to @Final field field_24285:[Ljava/lang/String; in wurst.mixins.json:SignEditScreenMixin::handler$zga004$onInit
[19:36:57] [Render thread/INFO]: Loaded 62 advancements
[19:36:57] [Render thread/INFO]: [STDOUT]: Brightness started at 16.0
[19:36:58] [WurstUpdater/INFO]: [STDOUT]: [Updater] Current version: 7.15.2
[19:36:58] [WurstUpdater/INFO]: [STDOUT]: [Updater] Latest version: 7.15.2
FATAL ERROR in native method: Thread[Render thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11.glShadeModel(Native Method)
	at net.wurstclient.hud.TabGui.render(TabGui.java:123)
	at net.wurstclient.hud.IngameHUD.onRenderGUI(IngameHUD.java:45)
	at net.wurstclient.events.GUIRenderListener$GUIRenderEvent.fire(GUIRenderListener.java:35)
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_329.handler$zfe000$onRender(class_329.java:1497)
	at net.minecraft.class_329.method_1753(class_329.java:384)
	at net.minecraft.class_757.method_3192(class_757.java:856)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@16.0.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@16.0.1/NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@16.0.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@16.0.1/Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@16.0.1/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@16.0.1/NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@16.0.1/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@16.0.1/Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process crashed with exitcode 6.
Clipboard copy at: 10 Jun 2021 19:38:35 -0700

```

 </details>

**Comment by Alexander01998** [comment]
Fixed in f64b156451aee843bfd88d858b67b921c34a7bb4.
