### ISSUE TITLE
Minecraft was Crash 

### ISSUE THREAD

**Issue by AdminHcat** [Wurst-Imperium/Wurst7#543]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. 
2. 
3. 

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

[spoiler]游戏核心：Fabric-0.12.12-1.18.1
启动内存：6000 MB
操作系统：Microsoft Windows 10 专业工作站版 x64
————————————————————
CPU：#0Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz 
内存：16297
显卡：#0NVIDIA GeForce GTX 1660 SUPER 
————————————————————
核心路径：D:\Minecraft\Game\.minecraft\versions\Fabric-0.12.12-1.18.1
Java信息：D:\JDK\openjdk-17.0.1\bin\javaw.exe (Java17.0.1.0 64 Bit)
BakaXL路径：D:\Minecraft\Game\BakaXL_Public_Ver_3.1.0.4.exe
————————————————————
错误日志：
---- Minecraft 崩溃报告 ----
// Don't do that.

Time: 2022/1/15 下午1:48
崩溃类型： Firing Wurst event

java.lang.ArrayIndexOutOfBoundsException: Index 108 out of bounds for length 108
	at java.base/java.util.HashMap.keysToArray(HashMap.java:950)
	at java.base/java.util.HashSet.toArray(HashSet.java:368)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at net.wurstclient.hacks.MobSpawnEspHack$ChunkScanner.compileBuffer(MobSpawnEspHack.java:358)
	at net.wurstclient.hacks.MobSpawnEspHack.onUpdate(MobSpawnEspHack.java:162)
	at net.wurstclient.events.UpdateListener$UpdateEvent.fire(UpdateListener.java:27)
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_746.handler$dji007$onTick(class_746.java:8370)
	at net.minecraft.class_746.method_5773(class_746.java:215)
	at net.minecraft.class_638.method_18646(class_638.java:218)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_638.method_32124(class_638.java:201)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:197)
	at net.minecraft.class_310.method_1574(class_310.java:1751)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.HashMap.keysToArray(HashMap.java:950)
	at java.base/java.util.HashSet.toArray(HashSet.java:368)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at net.wurstclient.hacks.MobSpawnEspHack$ChunkScanner.compileBuffer(MobSpawnEspHack.java:358)
	at net.wurstclient.hacks.MobSpawnEspHack.onUpdate(MobSpawnEspHack.java:162)
	at net.wurstclient.events.UpdateListener$UpdateEvent.fire(UpdateListener.java:27)
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_746.handler$dji007$onTick(class_746.java:8370)
	at net.minecraft.class_746.method_5773(class_746.java:215)
	at net.minecraft.class_638.method_18646(class_638.java:218)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_638.method_32124(class_638.java:201)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:197)

-- Affected event --
Details:
	Event class: net.wurstclient.events.UpdateListener$UpdateEvent
Stacktrace:
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_746.handler$dji007$onTick(class_746.java:8370)
	at net.minecraft.class_746.method_5773(class_746.java:215)
	at net.minecraft.class_638.method_18646(class_638.java:218)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_638.method_32124(class_638.java:201)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:197)
	at net.minecraft.class_310.method_1574(class_310.java:1751)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 33317298
	Entity Name: Hcat
	Entity's Exact location: -813611.30, 16.20, -728584.70
	Entity's Block location: World: (-813612,16,-728585), Section: (at 4,0,7 in -50851,1,-45537; chunk contains blocks -813616,-64,-728592 to -813601,319,-728577), Region: (-1590,-1424; contains chunks -50880,-45568 to -50849,-45537, blocks -814080,-64,-729088 to -813569,319,-728577)
	Entity's Momentum: 0.00, 0.42, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_638.method_32124(class_638.java:201)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:197)
	at net.minecraft.class_310.method_1574(class_310.java:1751)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Hcat'/33317298, l='ClientLevel', x=-813611.30, y=16.20, z=-728584.70]]
	Chunk stats: 256, 152 F: 511 L: 0 U: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (-195,75,58), Section: (at 13,11,10 in -13,4,3; chunk contains blocks -208,-64,48 to -193,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 52454 game time, 1337393350 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 4
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, Dramatic+Skys+Demo+1.4.zip, Hcati18n, 3D-Noteblock-Displays-1.18-V2.2.zip, unique-spawn-eggs-v1-3-1-18.zip, XeKr+redstone+display+1.18.zip, subtitle-color-highlights-v1-2.zip, mcwzh-meme.fc2e94e.zip, Restyled-Discs-Resource-Pack-1.18.1.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 592240840 bytes (564 MiB) / 4068474880 bytes (3880 MiB) up to 6291456000 bytes (6000 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 27097.54
	Virtual memory used (MB): 24501.97
	Swap memory total (MB): 10799.83
	Swap memory used (MB): 554.54
	JVM Flags: 1 total; -Xmx6000M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancementinfo: AdvancementInfo 1.18-fabric0.43.1-1.3
		amecsapi: Amecs API 1.3.3+mc1.18-pre1
		appleskin: AppleSkin mc1.18-2.2.0
		architectury: Architectury 3.2.60
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axolotlitemfix: Axolotl Item Fix 1.1.3
		betterf3: BetterF3 1.2.2
		betterthirdperson: Better Third Person 1.6.0
		blue_endless_jankson: jankson 1.2.1
		bobby: Bobby 3.1.0
		bsvsb: Better Sodium Video Settings Button 2.0.5
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.6.1
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		chat_heads: Chat Heads 0.6.0
		cleancut: CleanCut 1.18-4.0-fabric
		clearview: Lava Clear View 3.0.0
		clickthrough: ClickThrough 1.18-fabric0.43.1-0.4
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config: Cloth Config v6 6.1.48
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		coat: Coat 1.0.0-beta.15
		colorutility: ColorUtility 2.0.1
		com_googlecode_json-simple_json-simple: json-simple 1.1.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		command-gui-buttons: QuickBind 1.3+1.18.1
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		continuity: Continuity 1.0.3+1.18
		controlling: Controlling For Fabric 9.0.8
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cullleaves: Cull Leaves 2.3.2
		customskinloader: CustomSkinLoader 14.13-SNAPSHOT-309
		deathlog: DeathLog 0.2.6+1.18
		draggable-resource-packs: Draggable Resource Packs 2.0.0
		dynamicfps: Dynamic FPS 2.0.6
		easiervillagertrading: EasierVillagerTrading 1.18-fabric0.43.1-1.5.4
		editsign: EditSign 2.2.7
		effective: Effective 1.1
		eggtab: Egg Tab 2.1.0+1.16-fabric
		elativitymc_c2me-fabric_ver_1_18_libs_: libs 0.2.0+alpha.6.1
		enchdesc: EnchantmentDescriptions 9.0.4
		fabric: Fabric API 0.45.2+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		ferritecore: FerriteCore 4.0.0
		gbfabrictools: GBfabrictools 1.3.4+1.18
		highlighter: Highlighter 1.1.2
		ias: In-Game Account Switcher 7.1.3
		iceberg: Iceberg 1.0.38
		imblocker: IMBlockerFabric 1.0.17
		indium: Indium 1.0.2-alpha1+mc1.18
		inspecio: Inspecio 1.2.0+1.18
		inventoryprofilesnext: Inventory Profiles Next 1.2.3
		invmove: InvMove 1.18-0.1.0
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.4
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		litematica: Litematica 0.9.0
		lithium: Lithium 0.7.7
		malilib: MaLiLib 0.10.0-dev.26
		mcwifipnp: LAN World Plug-n-Play 1.5.3
		megane: megane 6.2.0
		megane-base: megane-base 6.2.0
		megane-fabric-transfer: megane-fabric-transfer 6.2.0+1.5.4-b4f4f6cda9
		megane-runtime: megane-runtime 6.2.0
		megane-vanilla: megane-vanilla 6.2.0+1.18.1
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.18.1
		minieffects: Mini Effects 4.0.0
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		mousetweaks: Mouse Tweaks 2.19
		mousewheelie: Mouse Wheelie 1.8.0+mc1.18-pre5
		multiconnect: MultiConnect 1.5.10
		multiconnect-api: MultiConnect API 1.5.10
		nbteditor: NBT Editor 1.1.0
		nimble: Nimble 2.1.1
		org_anarres_jcpp: jcpp 1.4.14
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		org_yaml_snakeyaml: snakeyaml 1.30
		pinglist: PingList 1.3.3
		pistorder: Pistorder 1.4.4
		reeses-sodium-options: Reese's Sodium Options 1.3.0
		replanter: Replanter 1.3
		roughlyenoughitems: Roughly Enough Items 7.1.361
		roughlyenoughresources: Roughly Enough Resources 2.3.0
		searchablecontainers: Searchable Containers 1.3
		shulker-dupe: Shulker Dupe 1.0.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		signtools: Sign Tools 1.0.0
		skinlayers: 3d Skin Layers 1.3.1
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.2
		sodium: Sodium 0.4.0-alpha5+build.9
		sodium-extra: Sodium Extra 0.3.7
		starlight: Starlight 1.0.0+fabric.d0a3220
		stendhal: Stendhal 1.2.0-1.18
		talkbubbles: Talk Bubbles 1.0.1
		tooltipfix: ToolTip Fix 1.0.4-1.18
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		tweakeroo: Tweakeroo 0.11.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.2
		viafabric: ViaFabric 0.4.5+254-main
		viafabric-mc118: ViaFabric for 1.18 0.4.5+254-main
		viaversion: ViaVersion 4.1.2-SNAPSHOT
		wildfire_gender: Wildfire's Female Gender Mod 2.8.1
		worldedit: WorldEdit 7.2.8+6008-1246d61
		wthit: wthit 4.4.0
		wurst: Wurst Client v7.19-MC1.18.1
		xaerominimap: Xaero's Minimap 21.23.0
		xhp: xhp 1.10.4
	Launched Version: Fabric-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 456.71, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, Fabric Mods, continuity/default, continuity/glass_pane_culling_fix, file/Dramatic+Skys+Demo+1.4.zip, file/Hcati18n, file/3D-Noteblock-Displays-1.18-V2.2.zip, file/unique-spawn-eggs-v1-3-1-18.zip, file/XeKr+redstone+display+1.18.zip, file/subtitle-color-highlights-v1-2.zip, file/mcwzh-meme.fc2e94e.zip, file/Restyled-Discs-Resource-Pack-1.18.1.zip
	Current Language: 简体中文 (中国)
	CPU: 16x Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz

[/spoiler]

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by ItzVaio** [comment]
this is just completely invalid you didnt put anything but the crash report
这只是完全无效的，你没有放任何东西，但崩溃报告
