### ISSUE TITLE
Bug while It starting

### ISSUE THREAD

**Issue by DongwonTTuna** [Wurst-Imperium/Wurst7#55]
## Steps to reproduce
I downloaded wurst7 sources then ./gradlew eclipse and I started eclipse.
I changed hacks/AutofishHacks.java 
		
                // right click
		IMC.rightClick();

to
		// right click
		IMC.rightClick();
		IMC.rightClick();
		IMC.rightClick();
		IMC.rightClick();
		IMC.rightClick();
		IMC.rightClick();

then ctrl+s to save and It automatically builded.
so I cut all of things that in workspace/bin folder

I removed assets,net folders and fabric.mod.json, wurst.mixins.json from original jar and pasted it on wurstclient.jar.
 
I'm really sorry that I'm new to java. but I can't find anything when I searched
'java.lang.ClassNotFoundException: net.minecraft.client.MinecraftClient'

thank you :)

## (Optional) screenshots / videos
If applicable, add screenshots or videos to help explain your problem.

## Versions
Please complete the following information:
- Minecraft version: [e.g. 1.14.4] 1.15.2
- Wurst version: [e.g. 7.0pre1] newest version

## Crash report
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 20. 2. 8 오후 12:35
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:392)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/client/MinecraftClient
		at net.wurstclient.WurstClient.<clinit>(WurstClient.java:50)
		at net.wurstclient.WurstInitializer.onInitialize(WurstInitializer.java:27)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1435/1371252597.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:48)
		... 11 more
	Caused by: java.lang.ClassNotFoundException: net.minecraft.client.MinecraftClient
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:392)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 294258560 bytes (280 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autofish: Autofish 0.8.5
		fabric: Fabric API 0.4.29+build.290-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.9+aea78a250c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.22+203491ea0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.8+build.184
		minecraft: Minecraft 1.15.2
		voxelmap: VoxelMap 1.9.14
		wurst: Wurst Client v7.0pre26-MC1.15.2
	Launched Version: fabric-loader-0.7.8+build.184-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

```
Please note: A log file or a picture of the launcher's "something went wrong" screen are _not_ the same as crash report. If the game didn't crash, please hold down F3+C for 10 seconds to generate a crash report.

**Comment by Alexander01998** [comment]
> I downloaded wurst7 sources then ./gradlew eclipse and I started eclipse.
> I changed hacks/AutofishHacks.java
> 
> ```
>             // right click
> 	IMC.rightClick();
> ```
> 
> to
> // right click
> IMC.rightClick();
> IMC.rightClick();
> IMC.rightClick();
> IMC.rightClick();
> IMC.rightClick();
> IMC.rightClick();
> 
> then ctrl+s to save and It automatically builded.
> so I cut all of things that in workspace/bin folder
> 
> I removed assets,net folders and fabric.mod.json, wurst.mixins.json from original jar and pasted it on wurstclient.jar.
> 
> I'm really sorry that I'm new to java. but I can't find anything when I searched
> 'java.lang.ClassNotFoundException: net.minecraft.client.MinecraftClient'
> 
> thank you :)

I'm sorry, but this couldn't possibly work. Removing that many necessary things and then trying to bypass the compiler is a recipe for disaster.
