### ISSUE TITLE
NukerLegit NullPointerException client crash

### ISSUE THREAD

**Issue by andrewprivate** [Wurst-Imperium/Wurst7#58]
Just turning on the feature will crash the client, and must be disabled manually via config files.

```
Caused by: java.lang.NullPointerException
	at net.minecraft.class_1937.method_8518(class_1937.java:162)
	at net.minecraft.class_1937.method_8320(class_1937.java:378)
	at net.wurstclient.util.BlockUtils.getState(BlockUtils.java:33)
	at net.wurstclient.hacks.AutoToolHack.getBestSlot(AutoToolHack.java:149)
	at net.wurstclient.hacks.AutoToolHack.equipBestTool(AutoToolHack.java:118)
	at net.wurstclient.hacks.AutoToolHack.equipIfEnabled(AutoToolHack.java:107)
	at net.wurstclient.hacks.NukerLegitHack.breakBlockExtraLegit(NukerLegitHack.java:207)
	at net.wurstclient.hacks.NukerLegitHack.onUpdate(NukerLegitHack.java:145)
	at net.wurstclient.events.UpdateListener$UpdateEvent.fire(UpdateListener.java:27)
	at net.wurstclient.event.EventManager.fire(EventManager.java:55)
	at net.minecraft.class_746.handler$zej000$onTick(class_746.java:1277)
	at net.minecraft.class_746.method_5773(class_746.java:204)
	at net.minecraft.class_638.method_18646(class_638.java:180)
	at net.minecraft.class_1937.method_18472(class_1937.java:534)
```

The cause of this problem is concerned with this line of code in NukerLegitHack.java in the function `breakBlockExtraLegit`

https://github.com/Wurst-Imperium/Wurst7/blob/42e0272b635cd17eee0096fb023f9b16c008e314/src/main/java/net/wurstclient/hacks/NukerLegitHack.java#L207

As you can see, the variable `currentBlock` is sent to the AutoTool function. However, a quick look at the caller of this function reveals an egregious programming mistake. 

https://github.com/Wurst-Imperium/Wurst7/blob/42e0272b635cd17eee0096fb023f9b16c008e314/src/main/java/net/wurstclient/hacks/NukerLegitHack.java#L128-L156
(box above is scrollable)

The `currentBlock` is set to `null` and then the `breakBlockExtraLegit` function is called immediately after. This means that in the first loop, the `currentBlock` variable will always be `null`. Which, of course, causes the crash since the `null` variable is used/sent to the AutoTool function by the `breakBlockExtraLegit` function.

**Comment by andrewprivate** [comment]
In my copy of the client, I created a quick hotfix by adding a quick conditional to check for null at line 207

https://github.com/Wurst-Imperium/Wurst7/blob/42e0272b635cd17eee0096fb023f9b16c008e314/src/main/java/net/wurstclient/hacks/NukerLegitHack.java#L207

To

```java
if(currentBlock != null) WURST.getHax().autoToolHack.equipIfEnabled(currentBlock); 
```

**Comment by andrewprivate** [comment]
@Alexander01998 Will this be fixed?

**Comment by This1sMyName** [comment]
Hi andreprivate i had the same bug. How do i download your copy of the client?

**Comment by Andrews54757** [comment]
Fixed in https://github.com/Wurst-Imperium/Wurst7/commit/7eea70d3ad1cb4ddd7554f50d9c1b6a0bbfc626c

**Comment by andrewprivate** [comment]
Fixed in https://github.com/Wurst-Imperium/Wurst7/commit/7eea70d3ad1cb4ddd7554f50d9c1b6a0bbfc626c
