### ISSUE TITLE
KillAura doesn't care about Criticals

### ISSUE THREAD

**Issue by KGriss** [Wurst-Imperium/Wurst7#60]
## Description
When I activate the KillAura (KillAuraLegit, MultiAura, TriggerBot, ... also) and the Criticals, the Criticals don't change the behavior of the KillAura. But when I attack an entity manually, the Criticals work correctly.

## Steps to reproduce
1. Run Wurst client 7.0 for Minecraft 1.15.2
2. Enable the KillAura (or any "AutoAttack" bot)
3. Enable the Criticals (any mode)
4. Get closer to an entity and see that KillAura ignores the fact that Criticals is enabled

## Versions
- Minecraft version: 1.15.2
- Wurst version: 7.0

## Crash report
```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2/21/20 7:16 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.class_309.method_1474(class_309.java:454)
	at net.minecraft.class_310.method_1574(class_310.java:1511)
	at net.minecraft.class_310.method_1523(class_310.java:964)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_309.method_1474(class_309.java:454)

-- Affected level --
Details:
	All players: 1 total; [class_746['MetalGriss'/132, l='MpServer', x=156.11, y=67.00, z=151.77]]
	Chunk stats: Client Chunk Cache: 841, 675
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 160550433344232043
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (144,65,144), Chunk: (at 0,4,0 in 9,9; contains blocks 144,0,144 to 159,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 41551 game time, 41551 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:634)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 906245304 bytes (864 MB) / 1668284416 bytes (1591 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 4
	JVM Flags: 4 total; -Xverify:none -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	Fabric Mods: 
		baritone: baritone 1.4.5
		fabric: Fabric API 0.4.29+build.290-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.9+aea78a250c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.22+203491ea0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.8+build.184
		minecraft: Minecraft 1.15.2
		wurst: Wurst Client v7.0-MC1.15.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 950M/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.66, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Français (France)
	CPU: 4x Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz

```

**Comment by andrewprivate** [comment]
Easy fix, add this one line before attacking in the killaura code

```java
if (WURST.getHax().criticalsHack.isEnabled()) WURST.getHax().criticalsHack.doCritical()
```

**Comment by dandud100** [comment]
> Easy fix, add this one line before attacking in the killaura code
> 
> ```java
> if (WURST.getHax().criticalsHack.isEnabled()) WURST.getHax().criticalsHack.doCritical()
> ```

Is it implented yet?

**Comment by KGriss** [comment]
That's not patched in 7.4
