### ISSUE TITLE
'wurst' seems to conflict with 'tweakermyclient', These two mods can't play the game together.

### ISSUE THREAD

**Issue by YZ-HZ** [Wurst-Imperium/Wurst7#605]
[15:29:49] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[15:29:50] [main/INFO]: Loading 81 mods:
	- appleskin 2.4.0+mc1.18.2
	- baritone 1.8.3
	- bedrockminer 1.0.0
	- betterf3 1.2.3
	- caffeineconfig 1.0.0 via sodium-extra
	- clientcommands 2.6.3
	- clientcommands-scripting 1.3.1 via clientcommands
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.0.42 via betterf3
	- conditional-mixin 0.2.0 via tweakermore
	- easiervillagertrading 1.18.2-fabric0.47.10-1.5.4
	- entityculling 1.5.0
	- fabric 0.48.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.2+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.3+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.2+2540745460 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- gbfabrictools 1.3.4+1.18.2 via easiervillagertrading
	- indium 1.0.2+mc1.18.2
	- iris 1.2.2-build.32
	- itemscroller 0.16.0
	- java 17
	- litematica 0.11.1
	- litematica_printer 2.1
	- lithium 0.7.9
	- magiclib 0.1.14 via tweakmyclient
	- malilib 0.12.1
	- minecraft 1.18.2
	- minihud 0.22.0
	- modmenu 3.1.0
	- multiconnect-api 1.5 via clientcommands
	- org_anarres_jcpp 1.4.14 via iris
	- org_joml_joml 1.10.2 via sodium
	- phosphor 0.8.1
	- reeses-sodium-options 1.4.2
	- shulker-dupe 1.0.0
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.2
	- tweakermore 2.8.0
	- tweakeroo 0.13.1
	- tweakmyclient 1.2.2+de14369
	- voxelmap 1.18.2-1.11.1
	- wurst v7.22-MC1.18.2
[15:29:50] [main/WARN]: Mod `wurst` (v7.22-MC1.18.2) does not respect SemVer - comparison support is limited.
[15:29:50] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Minecraft/%e5%85%a8%e9%9a%94%e7%a6%bb%e7%89%88%e6%9c%ac/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[15:29:50] [main/INFO]: Compatibility level set to JAVA_17
[15:29:50] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 0 override(s) found
[15:29:50] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[15:29:50] [main/INFO]: Loaded configuration file for Sodium Extra: 23 options available, 0 override(s) found
[15:29:51] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[15:29:51] [main/INFO]: [TweakerMore] Disabled mixin me.fallenbreath.tweakermore.mixins.tweaks.eCraftItemScrollerCompact.ConfigsMixin due to required mod easiercrafting not found
[15:29:51] [main/INFO]: [TweakerMore] Disabled mixin me.fallenbreath.tweakermore.mixins.tweaks.eCraftItemScrollerCompact.CraftingHandlerMixin due to required mixin class me.fallenbreath.tweakermore.mixins.tweaks.eCraftItemScrollerCompact.ConfigsMixin disabled
[15:29:51] [main/INFO]: [TweakerMore] Disabled mixin me.fallenbreath.tweakermore.mixins.tweaks.ofRemoveSignTextRenderDistance.SignBlockEntityRendererMixin due to required mod optifabric not found
[15:29:51] [main/INFO]: [TweakerMore] Disabled mixin me.fallenbreath.tweakermore.mixins.tweaks.ofUnlockF3FpsLimit.DebugHudMixin due to required mod optifabric not found
[15:29:51] [main/INFO]: [TweakerMore] Disabled mixin me.fallenbreath.tweakermore.mixins.tweaks.replayAccurateTimelineTimestamp.AbstractGuiTimelineMixin due to required mod replaymod not found
[15:29:51] [main/INFO]: [TweakerMore] Disabled mixin me.fallenbreath.tweakermore.mixins.tweaks.replayFlySpeedLimit.ClassicCameraControllerMixin due to required mod replaymod not found
[15:29:51] [main/INFO]: [TweakerMore] Disabled mixin me.fallenbreath.tweakermore.mixins.tweaks.replayFlySpeedLimit.VanillaCameraControllerMixin due to required mod replaymod not found
[15:29:51] [main/INFO]: [TweakerMore] Disabled mixin me.fallenbreath.tweakermore.mixins.tweaks.tweakmFlawlessFrames.ScreenshotRendererMixin due to required mod replaymod not found
[15:29:51] [main/INFO]: [TweakerMore] Disabled mixin me.fallenbreath.tweakermore.mixins.tweaks.tweakmFlawlessFrames.VideoRendererMixin due to required mod replaymod not found
[15:29:51] [main/INFO]: [TweakerMore] Disabled mixin me.fallenbreath.tweakermore.mixins.tweaks.xmapNoSessionFinalizationWait.WorldMapSessionMixin due to required mod xaeroworldmap not found
[15:29:51] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[15:29:56] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zhj000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[15:29:57] [main/WARN]: Method overwrite conflict for checkOpenWaterAround in wurst.mixins.json:FishingBobberEntityMixin, previously written by top.hendrixshen.TweakMyClient.mixin.feature.featureOpenWaterHelper.MixinFishingHook. Skipping method.
[15:30:00] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[15:30:00] [Render thread/INFO]: sodium-extra.mixins.json:gui.MinecraftClientAccessor->@Accessor[FIELD_GETTER]::getCurrentFPS()I should be static as its target is
[15:30:01] [Render thread/WARN]: @Redirect conflict. Skipping wurst.mixins.json:ClientPlayerEntityMixin->@Redirect::wurstIsUsingItem(Lnet/minecraft/class_746;)Z from mod wurst with priority 1000, already redirected by TweakMyClient.mixins.json:disable.disableSlowdown.MixinLocalPlayer->@Redirect::getUsingItemState(Lnet/minecraft/class_746;)Z from mod tweakmyclient with priority 1000
[15:30:01] [Render thread/WARN]: @Redirect conflict. Skipping wurst.mixins.json:ClientPlayerEntityMixin->@Redirect::wurstIsUsingItem(Lnet/minecraft/class_746;)Z from mod wurst with priority 1000, already redirected by TweakMyClient.mixins.json:disable.disableSlowdown.MixinLocalPlayer->@Redirect::getUsingItemState(Lnet/minecraft/class_746;)Z from mod tweakmyclient with priority 1000
[15:30:01] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_746 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_746 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[1.18.2-Fabric%200.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[1.18.2-Fabric%200.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector wurstIsUsingItem(Lnet/minecraft/class_746;)Z in wurst.mixins.json:ClientPlayerEntityMixin from mod wurst failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Wurst-Client-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[1.18.2-Fabric%200.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more

**Comment by warmbroke** [comment]
This is not a bug. The two mods happen to be Redirecting the same method, providing the same NoSlowDown function. AND THERE IS NO FIX FOR THAT.  
[first](https://github.com/Hendrix-Shen/Tweak-My-Client/blob/85f7eb762820553db186ae986dfc2553e3e72cce/src/main/java/top/hendrixshen/tweakmyclient/mixin/disable/disableSlowdown/MixinLocalPlayer.java#L22)
[second](https://github.com/Wurst-Imperium/Wurst7/blob/a20936c30ef61bc1a0f828aceb53354be77f20f4/src/main/java/net/wurstclient/mixin/ClientPlayerEntityMixin.java#L98)
Luckily [Tweak-My-Client](https://github.com/Hendrix-Shen/Tweak-My-Client) has merely one Redirect in `disable.disableSlowdown.MixinLocalPlayer`, making it possible to extract the jar file, delete the `disable.disableSlowdown.MixinLocalPlayer` line, and then reassemble the jar file.  
It shoud let you launch the game, the disableSlowdown function of Tweak-My-Client won't work properly after that though.
