### ISSUE TITLE
Wurst Crashing with Mathax

### ISSUE THREAD

**Issue by rusian85** [Wurst-Imperium/Wurst7#607]
[15:29:38] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[15:29:39] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) 0.4.2 recommends version 1.4.2 or later of reeses-sodium-options, which is missing!
	 - You should install version 1.4.2 or later of reeses-sodium-options for the optimal experience.
[15:29:39] [main/INFO]: Loading 60 mods:
	- baritone 1.18.2-SNAPSHOT via mathax
	- caffeineconfig 1.0.0 via sodium-extra
	- fabric 0.48.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.2+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.3+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.2+2540745460 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- ferritecore 4.2.0
	- java 17
	- lithium 0.7.9
	- mathax 1.7.4
	- minecraft 1.18.2
	- org_joml_joml 1.10.2 via sodium
	- org_yaml_snakeyaml 1.30 via viafabric
	- smoothboot 1.18.2-1.7.0
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.2
	- starlight 1.0.2+fabric.89b8d9f
	- viafabric 0.4.6+266-main
	- viafabric-mc118 0.4.6+266-main via viafabric
	- viaversion 4.2.1 via viafabric
	- wurst v7.22-MC1.18.2
[15:29:43] [main/WARN]: Mod `wurst` (v7.22-MC1.18.2) does not respect SemVer - comparison support is limited.
[15:29:43] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Rusian85_YT/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[15:29:43] [main/INFO]: Compatibility level set to JAVA_17
[15:29:43] [main/INFO]: Loaded configuration file for Lithium: 100 options available, 1 override(s) found
[15:29:44] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[15:29:44] [main/INFO]: Loaded configuration file for Sodium Extra: 23 options available, 0 override(s) found
[15:29:44] [main/WARN]: Mixin malte0811.ferritecore.mixin.threaddetec.PalettedContainerMixin is disabled automatically as lithium is installed
[15:29:44] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[15:29:44] [main/WARN]: Error loading class: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen (java.lang.ClassNotFoundException: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen)
[15:29:45] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[15:29:45] [main/INFO]: Smooth Boot config initialized
[15:29:47] [main/WARN]: Method overwrite conflict for getBlockEntityTickers in mathax.mixins.json:WorldAccessor, previously written by net.wurstclient.mixin.WorldMixin. Skipping method.
[15:29:49] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zdp000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[15:29:53] [Render thread/WARN]: Method overwrite conflict for setSession in mathax.mixins.json:MinecraftClientAccessor, previously written by net.wurstclient.mixin.MinecraftClientMixin. Skipping method.
[15:29:53] [Render thread/WARN]: Method overwrite conflict for setItemUseCooldown in mathax.mixins.json:MinecraftClientAccessor, previously written by net.wurstclient.mixin.MinecraftClientMixin. Skipping method.
[15:29:53] [Render thread/WARN]: Method overwrite conflict for getItemUseCooldown in mathax.mixins.json:MinecraftClientAccessor, previously written by net.wurstclient.mixin.MinecraftClientMixin. Skipping method.
[15:29:53] [Render thread/INFO]: sodium-extra.mixins.json:gui.MinecraftClientAccessor->@Accessor[FIELD_GETTER]::getCurrentFPS()I should be static as its target is
[15:29:53] [Render thread/WARN]: @Redirect conflict. Skipping wurst.mixins.json:ClientPlayerEntityMixin->@Redirect::wurstIsUsingItem(Lnet/minecraft/class_746;)Z from mod wurst with priority 1000, already redirected by mathax.mixins.json:ClientPlayerEntityMixin->@Redirect::redirectUsingItem(Lnet/minecraft/class_746;)Z from mod mathax with priority 1000
[15:29:54] [Render thread/WARN]: @Redirect conflict. Skipping wurst.mixins.json:ClientPlayerEntityMixin->@Redirect::wurstIsUsingItem(Lnet/minecraft/class_746;)Z from mod wurst with priority 1000, already redirected by mathax.mixins.json:ClientPlayerEntityMixin->@Redirect::redirectUsingItem(Lnet/minecraft/class_746;)Z from mod mathax with priority 1000
[15:29:54] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_746 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_746 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[Fabric%201.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at mathax.client.asm.Asm$Transformer.transformClassBytes(Asm.java:97) ~[MatHax-v1.7.4-Fabric_1.18.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[Fabric%201.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector wurstIsUsingItem(Lnet/minecraft/class_746;)Z in wurst.mixins.json:ClientPlayerEntityMixin from mod wurst failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Wurst-Client-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at mathax.client.asm.Asm$Transformer.transformClassBytes(Asm.java:97) ~[MatHax-v1.7.4-Fabric_1.18.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[Fabric%201.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more

**Comment by InfinitePower563** [comment]
Mathax/Meteor cannot have Fabric API for some reason, and Wyrst requires Fabric API.

**Comment by warmbroke** [comment]
You really should ask Mathax/Meteor to fix their compatibility with Fabric API instead.

**Comment by warmbroke** [comment]
Also you shouldn't be using 2 hacked clients at the same time.

**Comment by ItzVaio** [comment]
> Mathax/Meteor cannot have Fabric API for some reason, and Wyrst requires Fabric API.

Meteor does not support fabric api, having some rendering issues with it. But even when it's in them mod folder its still fine,
And wurst is not an addon of meteor so there is bit of a conflict into both UI's opening at same time.
