### ISSUE TITLE
Fabritone incompatible

### ISSUE THREAD

**Issue by a89792** [Wurst-Imperium/Wurst7#61]
## Description
Autofish will disconnect when fabritone(baritone) loaded in a server game(single not test).

## Versions
- Minecraft version: [1.15.2](other version not test)
- Wurst version: 7.0pre27,7.0 (other version not test)

## Crash report
```

[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: java.lang.IllegalStateException
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at baritone.utils.BlockStateInterface.<init>(BlockStateInterface.java:76)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at baritone.utils.BlockStateInterface.<init>(BlockStateInterface.java:63)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at baritone.utils.BlockStateInterface.<init>(BlockStateInterface.java:59)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at baritone.utils.BlockStateInterface.get(BlockStateInterface.java:91)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at baritone.utils.BlockStateInterface.getBlock(BlockStateInterface.java:87)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at baritone.behavior.MemoryBehavior.onBlockInteract(MemoryBehavior.java:52)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.lambda$onBlockInteract$12(GameEventHandler.java:147)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at baritone.event.GameEventHandler.onBlockInteract(GameEventHandler.java:147)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_310.handler$zbp000$onBlockUse(class_310.java:3680)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1583(class_310.java:1386)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_310.rightClick(class_310.java:4138)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at net.wurstclient.hacks.AutoFishHack.rightClick(AutoFishHack.java:295)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at net.wurstclient.hacks.AutoFishHack.onReceivedPacket(AutoFishHack.java:283)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at net.wurstclient.events.PacketInputListener$PacketInputEvent.fire(PacketInputListener.java:40)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at net.wurstclient.event.EventManager.fire(EventManager.java:55)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_2535.handler$zcn000$onChannelRead0(class_2535.java:1036)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_2535.method_10770(class_2535.java:148)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at net.minecraft.class_2535.channelRead0(class_2535.java:53)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[13:46:32] [Netty Client IO #0/INFO]: [STDERR]: 	at java.lang.Thread.run(Unknown Source)

```
What is displayed on the screen:"Internal Exception:net.minecraft.class_148:Firing Wurst event"

**Comment by KGriss** [comment]
What version of Fabritone are you using ?

**Comment by a89792** [comment]
> What version of Fabritone are you using ?

1.5.1
gitlab.com/CDAGaming/fabritone/-/commit/aba4283b2b3850f2edfd1df2e63f546f524fb1d3

**Comment by jhonnystene** [comment]
AutoFish working as intended for me with Fabritone. What other mods do you have installed?

**Comment by JamesTheAwesomeDude** [comment]
it works for me, on Fabritone 1.6.2 and Baritone's mainline Fabric support in 1.6.3

Are you trying to fish and pathfind at the same time or something?

**Comment by Alexander01998** [comment]
Closing this issue as it seems to be resolved. If it isn't, please let me know.
