### ISSUE TITLE
Optifine or optifabric incompatible

### ISSUE THREAD

**Issue by a89792** [Wurst-Imperium/Wurst7#62]
## Description
Crash in game loading when use optifabric

## Steps to reproduce
Crash before game loading

## Versions
Please complete the following information:
- Minecraft version: 1.15.2
- Wurst version: 7.0pre27,7.0(but 7.0pre26 is ok)

## Crash report
```
[15:24:28] [main/INFO]: Loading for game Minecraft 1.15.2
[15:24:31] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-keybindings-v0: used 0.1.1+933c24c242, also found 0.1.1+dfdb52d60c
 - Conflicting versions found for fabric-api-base: used 0.1.2+28f8190f42, also found 0.1.2+b7f9825d0c
 - Conflicting versions found for fabric-networking-v0: used 0.1.7+12515ed90c, also found 0.1.7+12515ed995
 - Conflicting versions found for fabric-events-interaction-v0: used 0.2.7+a1bd31180c, also found 0.2.7+a1bd311895
 - Mod amecs conflicts with mod {optifabric @ [*]}, but the conflicting version is present: 1.0.0-beta4!
 - Conflicting versions found for fabric-resource-loader-v0: used 0.1.10+06c939b395, also found 0.1.10+06c939b30c
 - Conflicting versions found for fabric-tag-extensions-v0: used 0.1.3+d423005742, also found 0.1.3+abd915800c
 - Conflicting versions found for fabric-mining-levels-v0: used 0.1.1+28f8190f42, also found 0.1.1+b7f9825d0c
 - Conflicting versions found for fabric-events-lifecycle-v0: used 0.1.2+b7f9825de8, also found 0.1.2+b7f9825d0c
[15:24:31] [main/WARN]: Mod `tweed` (2.2.8) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[15:24:31] [main/INFO]: [FabricLoader] Loading 62 mods: fabric-renderer-api-v1@0.2.10+f08b61330c, fabric-keybindings-v0@0.1.1+933c24c242, gbfabrictools@1.1.0, fabricloader@0.7.8+build.184, org_zeroturnaround_zt-zip@1.14, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.2.4+203491ea0c, fabric-api-base@0.1.2+28f8190f42, mm@2.0, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, fabric-textures-v0@1.0.4+821cdba70c, fabric-rendering-fluids-v1@0.1.6+12515ed90c, easiervillagertrading@1.14.4-fabric0.4.1-1.4, waila@1.9.19, me_shedaniel_cloth_basic-math@0.3.0, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, autoharvest@1.0.4, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric@0.4.32+build.292-1.15, org_slf4j_slf4j-api@1.7.30, fabric-particles-v1@0.1.1+dfdb52d60c, fabric-networking-v0@0.1.7+12515ed90c, cloth@1.1.0, okzoomer@2.1.2, minecraft@1.15.2, fabric-networking-blockentity-v0@0.2.3+e08a73050c, modmenu@1.10.1+build.30, phosphor@0.3.6, fabric-renderer-indigo@0.2.23+9290e2ed0c, fabritone@1.5.1, fabric-biomes-v1@0.1.5+3b05f68e0c, roughlyenoughitems@3.3.14, org_slf4j_slf4j-simple@1.7.30, fabric-events-interaction-v0@0.2.7+a1bd31180c, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, orderly@1.2.0+build.1-1.15, fabric-rendering-v0@1.1.0+534104900c, mousewheelie@1.4.0+1.15.2-pre1, fabric-rendering-v1@0.1.0+534104900c, cloth-config2@2.9.3, amecs@1.2.9+1.15-pre5, autoconfig1u@1.2.4, fabric-resource-loader-v0@0.1.10+06c939b395, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+d423005742, optifabric@1.0.0-beta4, appleskin@1.0.8, flighthelper@1.15-fabric0.4.23-1.2, fabric-commands-v0@0.1.2+b7f9825d0c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, durabilityviewer@1.15-fabric0.4.23-1.5, fabric-mining-levels-v0@0.1.1+28f8190f42, voxelmap@1.9.14, fabric-events-lifecycle-v0@0.1.2+b7f9825de8, wurst@v7.0-MC1.15.2, fabric-item-groups-v0@0.1.6+ec40b2e10c, fabric-models-v0@0.1.0+dfdb52d60c, shulkerboxtooltip@1.4.5+1.15, fabric-object-builders-v0@0.1.3+e4c9a9c30c, tweed@2.2.8, org_jetbrains_annotations@18.0.0
[15:24:31] [main/WARN]: Mod `wurst` (v7.0-MC1.15.2) does not respect SemVer - comparison support is limited.
[15:24:31] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/xghxx1.15.2/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[15:24:31] [main/WARN]: Reference map 'optifabric-refmap.json' for optifabric.mixins.json could not be read. If this is a development environment you can ignore this message
[15:24:31] [main/WARN]: Reference map 'AutoHarvest-refmap.json' for modid.mixins.json could not be read. If this is a development environment you can ignore this message
[15:24:32] [main/WARN]: Reference map 'optifabric-refmap.json' for optifabric.indigofix.mixins.json could not be read. If this is a development environment you can ignore this message
[15:24:32] [main/WARN]: Reference map 'optifabric-refmap.json' for optifabric.optifine.mixins.json could not be read. If this is a development environment you can ignore this message
[15:24:32] [main/INFO]: [OptiFine] *** Reflector Forge ***
[15:24:32] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient

[GAME][2020/2/22/周六 15:24:32][15:24:32] [main/INFO]: [OptiFine] *** Reflector Forge ***
[GAME][2020/2/22/周六 15:24:32][15:24:32] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[GAME][2020/2/22/周六 15:24:33]org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector wurstGetSubmergedFluidState(Lnet/minecraft/class_4184;)Lnet/minecraft/class_3610; in wurst.mixins.json:BackgroundRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Wurst-Client-refmap.json
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
[GAME][2020/2/22/周六 15:24:33]	at java.lang.ClassLoader.loadClass(Unknown Source)
[GAME][2020/2/22/周六 15:24:33]	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:183)
[GAME][2020/2/22/周六 15:24:33]	at net.minecraft.class_128.method_559(class_128.java:101)
[GAME][2020/2/22/周六 15:24:33]	at net.minecraft.class_128.<init>(class_128.java:54)
[GAME][2020/2/22/周六 15:24:33]	at net.minecraft.class_128.method_24305(class_128.java:414)
[GAME][2020/2/22/周六 15:24:33]	at net.minecraft.client.main.Main.main(Main.java:129)
[GAME][2020/2/22/周六 15:24:33]	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[GAME][2020/2/22/周六 15:24:33]	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[GAME][2020/2/22/周六 15:24:33]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[GAME][2020/2/22/周六 15:24:33]	at java.lang.reflect.Method.invoke(Unknown Source)
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[GAME][2020/2/22/周六 15:24:33]Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:195)
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[GAME][2020/2/22/周六 15:24:33]Caused by: java.lang.reflect.InvocationTargetException
[GAME][2020/2/22/周六 15:24:33]	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[GAME][2020/2/22/周六 15:24:33]	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[GAME][2020/2/22/周六 15:24:33]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[GAME][2020/2/22/周六 15:24:33]	at java.lang.reflect.Method.invoke(Unknown Source)
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
[GAME][2020/2/22/周六 15:24:33]	... 2 more
[GAME][2020/2/22/周六 15:24:33]Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
[GAME][2020/2/22/周六 15:24:33]	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
[GAME][2020/2/22/周六 15:24:33]	at java.lang.ClassLoader.loadClass(Unknown Source)
[GAME][2020/2/22/周六 15:24:33]	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:183)
[GAME][2020/2/22/周六 15:24:33]	at net.minecraft.class_128.method_559(class_128.java:101)
[GAME][2020/2/22/周六 15:24:33]	at net.minecraft.class_128.<init>(class_128.java:54)
[GAME][2020/2/22/周六 15:24:33]	at net.minecraft.class_128.method_24305(class_128.java:414)
[GAME][2020/2/22/周六 15:24:33]	at net.minecraft.client.main.Main.main(Main.java:129)
[GAME][2020/2/22/周六 15:24:33]	... 7 more
[GAME][2020/2/22/周六 15:24:33]Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector wurstGetSubmergedFluidState(Lnet/minecraft/class_4184;)Lnet/minecraft/class_3610; in wurst.mixins.json:BackgroundRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Wurst-Client-refmap.json
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[GAME][2020/2/22/周六 15:24:33]	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[GAME][2020/2/22/周六 15:24:33]	... 18 more
[GAME][2020/2/22/周六 15:24:33]
[GAME][2020/2/22/周六 15:24:33]
[INFO][2020/2/22/周六 15:24:33]游戏进程退出，代码:1

```

**Comment by hanghang0702** [comment]
The same. I have Minecraft 1.14.4, Wurst v7.0, optifabric0.7.1, fabric api 0.4.2 (build 246) and OptiFine HD_U_ F5.
```
[19:50:42] [main/INFO]: Loading for game Minecraft 1.14.4
[19:50:47] [main/INFO]: [FabricLoader] Loading 36 mods: minecraft@1.14.4, fabric-renderer-api-v1@0.1.1+933c24c242, fabric-networking-blockentity-v0@0.2.1+28f8190f42, fabric-keybindings-v0@0.1.1+933c24c242, fabricloader@0.7.8+build.184, org_zeroturnaround_zt-zip@1.13, fabric-renderer-indigo@0.1.14+28f8190f42, fabric-containers-v0@0.1.3+28f8190f42, fabric-dimensions-v1@0.1.1+28f8190f42, fabric-biomes-v1@0.1.1+28f8190f42, org_slf4j_slf4j-simple@1.7.29, fabric-crash-report-info-v1@0.1.2+28f8190f42, fabric-events-interaction-v0@0.1.2+28f8190f42, fabric-api-base@0.1.2+28f8190f42, fabric-rendering-v0@0.1.2+28f8190f42, fabric-rendering-data-attachment-v1@0.1.2+28f8190f42, mm@1.8, fabric-resource-loader-v0@0.1.4+28f8190f42, fabric-textures-v0@0.1.4+933c24c242, fabric-content-registries-v0@0.1.2+28f8190f42, fabric-tag-extensions-v0@0.1.3+d423005742, optifabric@0.7.1, fabric-rendering-fluids-v1@0.1.3+28f8190f42, fabric-commands-v0@0.1.2+28f8190f42, fabric-registry-sync-v0@0.2.3+28f8190f42, fabric-mining-levels-v0@0.1.1+28f8190f42, fabric-loot-tables-v1@0.1.1+28f8190f42, fabric-events-lifecycle-v0@0.1.1+28f8190f42, fabric@0.4.2+build.246-1.14, wurst@v7.0-MC1.14.4, org_slf4j_slf4j-api@1.7.29, fabric-particles-v1@0.1.1+933c24c242, fabric-models-v0@0.1.0+933c24c242, fabric-item-groups-v0@0.1.1+28f8190f42, fabric-object-builders-v0@0.1.2+28f8190f42, fabric-networking-v0@0.1.4+28f8190f42
[19:50:47] [main/WARN]: Mod `wurst` (v7.0-MC1.14.4) does not respect SemVer - comparison support is limited.
[19:50:47] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/D:/PanDownloads/Modpacks/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
Found existing patched optifine jar, using that
[19:50:49] [main/INFO]: [OptiFine] *** Reflector Forge ***
[19:50:49] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector wurstGetSubmergedFluidState(Lnet/minecraft/class_4184;)Lnet/minecraft/class_3610; in wurst.mixins.json:BackgroundRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Wurst-Client-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:197)
	at net.minecraft.class_3268.<clinit>(class_3268.java:82)
	at net.minecraft.class_1066.<init>(class_1066.java:61)
	at net.minecraft.class_310.<init>(class_310.java:351)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:195)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:197)
	at net.minecraft.class_3268.<clinit>(class_3268.java:82)
	at net.minecraft.class_1066.<init>(class_1066.java:61)
	at net.minecraft.class_310.<init>(class_310.java:351)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector wurstGetSubmergedFluidState(Lnet/minecraft/class_4184;)Lnet/minecraft/class_3610; in wurst.mixins.json:BackgroundRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Wurst-Client-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 26 more
Exiting with -1
Process exited with code -1.

```
