### ISSUE TITLE
log message: Failed to load capes from wurstclient.net! (Wurst 6.35.3 MC1.12 OF)

### ISSUE THREAD

**Issue by Right2TheV0id** [Wurst-Imperium/Wurst7#663]
## Description
.minecraft/logs files flooded with "Failed to load capes from wurstclient.net!" error and its stack trace
This doesn't seem to alter the ingame experience, however I suspect that it might send a lot of (in this case, unnecessary) requests to access the capes list.

## Steps To Reproduce
1. Connect to a server (single player or not)
2. Open latest.log file
3. Voilà

## Crash Report
```

[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at net.wurstclient.hooks.CapesHook.checkCape(CapesHook.java:37)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at net.minecraft.client.resources.SkinManager$3.run(SkinManager.java:173)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:745)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.validator.Validator.validate(Validator.java:260)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	... 17 more
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: 	... 23 more

```

Didn't include a crash report as it does not seem relevant.
Please tell me if you really need one.

I extracted only the times at which the error occurs to give an idea of the frequence:

```

01:20:36] [pool-2-thread-3/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:20:36] [pool-2-thread-3/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:03] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:03] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:03] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:03] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:03] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:03] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:03] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:03] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:04] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:04] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:04] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:04] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:04] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:04] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:04] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:04] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:04] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:05] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:05] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:05] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:05] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:05] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:05] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:05] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:05] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:06] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:06] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:06] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:06] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:06] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:06] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:06] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:06] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:06] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:07] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:07] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:07] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:07] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:07] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:07] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:07] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:07] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:08] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:08] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:08] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:08] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:08] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:08] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:08] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:08] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:08] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:09] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:09] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:09] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:09] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:09] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:09] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:09] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:09] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:09] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:10] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:10] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:10] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:10] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:10] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:10] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:10] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:10] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:11] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:11] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:11] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:11] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:11] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:11] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:11] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:11] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:12] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:12] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:12] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[01:53:54] [pool-2-thread-4/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:06] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:06] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:11] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:25:59] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:06] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:06] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:07] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:08] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:09] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:10] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!
[02:26:26] [pool-2-thread-5/INFO]: [STDERR]: [Wurst] Failed to load capes from wurstclient.net!

```

From memory the problem occured in preceding 6.35 versions, but wasn't a big issue because I was not parsing log files to extract informations back in the days.

**Comment by Right2TheV0id** [comment]
That was it!
Thank you :)
