### ISSUE TITLE
Some bugs I've found after some extensive testing

### ISSUE THREAD

**Issue by TheWienerMaster** [Wurst-Imperium/Wurst7#67]
## Description
Gui bugs:
Killaura has an option to attack through walls but there is no way to choose it in the gui (you can only set it as true in  navigator.json file)
Navigator (right shift gui) scroll bar freezes when you use your mouse to drag it (no scrollwheel)
While editing basefinder or xray the blocks behind the imput box render through, so you can't always see what you typed
Multiaura, killaura, fightbot and killaura legit menu is a bit buggy on the right (right shift gui(navigator))

Cheat bugs:
Autoeat and buildrandom don't detect offhand
Server cleanup doesn't remember preferences (Maybe it's intended this way but I've already had some "happy little accidents")
.follow - only way to stop following is to enter an invalid entity
Server finder doesn't detect easy ip's like ngrok (example of ngrok ip's: 0.tcp.eu.ngrok.io:16121; 0.tcp.eu.ngrok.io:17468 (also works with us,ap,au,sa,jp,in;example: 0.tcp.us.ngrok.io:1xxxx))

Search feature doesn't always update correctly after entering a new dimension. It finds all the new blocks, but also misremembers the old blocks from the previous dimension. 
Re-enabling the feature doesn't fix it, only if you unrender the chucks and come back does it fix itself

## Steps to reproduce
Search bug-
1) Search obsidian (for example)
2) Go to end
3) After the pillars have loaded disable search
4) Go back to the overworld
5) Go to nether
6) Re-enable search and you should see huge obsidian pillars that actually aren't there

## Screenshots
Basefinder and xray gui problem
![image](https://user-images.githubusercontent.com/61437644/75203464-d0428800-5776-11ea-9c0f-e92c7629e187.png)

Multiaura, killaura, fightbot and killaura legit menu
![image](https://user-images.githubusercontent.com/61437644/75204688-37ae0700-577a-11ea-8497-bfd907ec68d7.png)

## Versions
- Minecraft version: 1.15.2
- Wurst version: Wurst-Client-v7.0-MC1.15.2
- Fabritone: 1.5.1
- Fabric: fabric-api-0.4.29+build.290-1.15
(don't have any more mods or even resource packs)
P.s These are the only bugs I've found(besides the fabritone esp and criticals not working with killauara but they're already mentioned), everything else works great. Keep doing god's work!

## Crash report (without fabritone)
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 25.02.20 2:39
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.class_309.method_1474(class_309.java:454)
	at net.minecraft.class_310.method_1574(class_310.java:1511)
	at net.minecraft.class_310.method_1523(class_310.java:964)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_309.method_1474(class_309.java:454)

-- Affected level --
Details:
	All players: 1 total; [class_746['TheWienerMaster'/2994, l='MpServer', x=-21.72, y=76.00, z=23.14]]
	Chunk stats: Client Chunk Cache: 1225, 841
	Level dimension: minecraft:the_nether
	Level name: MpServer
	Level seed: -1588835823423062078
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-94,74,256), Chunk: (at 2,4,0 in -6,16; contains blocks -96,0,256 to -81,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 265838 game time, 265838 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:634)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 837476440 bytes (798 MB) / 1509949440 bytes (1440 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.4.29+build.290-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.9+aea78a250c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.22+203491ea0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabricloader: Fabric Loader 0.7.6+build.180
		minecraft: Minecraft 1.15.2
		wurst: Wurst Client v7.0-MC1.15.2
	Launched Version: fabric-loader-0.7.6+build.180-1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (Canada)
	CPU: 6x Intel(R) Core(TM) i5-9600KF CPU @ 3.70GHz
```

**Comment by p3iurhgmc98h** [comment]
Regarding _.follow_, I think it's also possible to disable it through the navigator/clickGUI.

**Comment by TheWienerMaster** [comment]
Ohh you're right, it's just that you have to put it in as a command for it to work, so I assumed like with many other similar features, typing .follow with nothing behind it would work, but it doesn't. I guess you could disable it in gui even though that's a bit counter-intuitive in my opinion
