### ISSUE TITLE
Incompatible with Enhanced Block Entities mod

### ISSUE THREAD

**Issue by Xiaohei890510** [Wurst-Imperium/Wurst7#684]
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 7/19/22, 10:14 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'enhancedblockentities'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:443)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at net.fabricmc.fabric.api.renderer.v1.material.BlendMode.<clinit>(BlendMode.java:33)
		at link.infra.indium.renderer.RenderMaterialImpl.<clinit>(RenderMaterialImpl.java:34)
		at link.infra.indium.renderer.IndiumRenderer.materialFinder(IndiumRenderer.java:49)
		at link.infra.indium.renderer.IndiumRenderer.<clinit>(IndiumRenderer.java:32)
		at link.infra.indium.Indium.onInitializeClient(Indium.java:124)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 15 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at foundationgames.enhancedblockentities.EBESetup.setupChests(EBESetup.java:246)
	at foundationgames.enhancedblockentities.EnhancedBlockEntities.load(EnhancedBlockEntities.java:51)
	at foundationgames.enhancedblockentities.EnhancedBlockEntities.onInitializeClient(EnhancedBlockEntities.java:32)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 15 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 20 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 24 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onRenderWorldViewBobbing(Lnet/minecraft/class_757;Lnet/minecraft/class_4587;F)V in wurst.mixins.json:GameRendererMixin from mod wurst failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Wurst-Client-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 27 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:443)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:進階 Windows 32 基礎 API:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:使用者經驗控制項程式庫:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS 用戶端 API DLL:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP 協助程式 API:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API 用戶端 DLL:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API 用戶端 DLL:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF 伺服器 DLL:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows 效能資料協助程式 DLL:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:遠端程序呼叫執行階段:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows 殼層通用 Dll:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:多使用者 Windows USER API 用戶端 DLL:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft? C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP 服務:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI 應用程式介面動態連結程式庫:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32 位元 DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows 鎖定原則:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:應用程式相容性用戶端程式庫:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		bcrypt.dll:Windows 密碼編譯基本程式庫:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:用於 Windows 的 Microsoft COM:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP 用戶端服務:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 用戶端:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		fastprox.dll:WMI Custom Marshaller:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec 使用者模式 API:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		javaw.exe:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		jemalloc.dll
		jimage.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		jli.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		jna8505790739403074682.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jsvml.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		jvm.dll:Java HotSpot(TM) 64-Bit server VM:17.0.3.1:Oracle Corporation
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		management_ext.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		msvcp140.dll:Microsoft? C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft? C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 服務提供者:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:電子郵件命名 Shim 提供程式:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt 路由器:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		nio.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		ntdll.dll:NT 階層 DLL:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		ole32.dll:用於 Windows 的 Microsoft OLE:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows 系統效能物件 DLL:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP 命名空間提供者:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:殼層輕型公用程式程式庫:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		ucrtbase.dll:Microsoft? C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme 程式庫:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft? C Runtime Library:14.28.29913.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
		wbemcomn.dll:WMI:10.0.19041.1566 (WinBuild.160101.0800):Microsoft Corporation
		wbemprox.dll:WMI:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		wbemsvc.dll:WMI:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		win32u.dll:Win32u:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT 儲存 API:10.0.19041.1826 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Java(TM) Platform SE binary:17.0.3.1:Oracle Corporation
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 194057728 bytes (185 MiB) / 625999872 bytes (597 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.71
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 720
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1288
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7347
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 21276.80
	Virtual memory used (MB): 9272.45
	Swap memory total (MB): 13155.20
	Swap memory used (MB): 423.51
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	Fabric Mods: 
		alternate-current: Alternate Current 1.4.0
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.9.31
		betterf3: BetterF3 1.3.1
		betterpingdisplay: Better Ping Display 1.1.1
		clientcommands: Client Commands 2.7
			clientarguments: clientarguments 1.4.1
			multiconnect-api: MultiConnect API 1.5.10
		cloth-config: Cloth Config v6 7.0.73
			cloth-basic-math: cloth-basic-math 0.6.1
		controlling: Controlling For Fabric 10.0+1
		cull-less-leaves: Cull Less Leaves 1.0.4
			com_github_llamalad7_mixinextras: mixinextras 0.0.11
			conditional-mixin: conditional mixin 0.3.0
		dashloader: DashLoader 4.0.0+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		ferritecore: FerriteCore 4.2.1
		flighthelper: FlightHelper 1.19-fabric0.53.3-1.2.2
			gbfabrictools: GBfabrictools 1.3.4+1.19
		fpsreducer: FPS Reducer 1.19-2.0.1
		fvt: Flour's Various Tweaks 1.11.0-mc1.19
		indium: Indium 1.0.6+mc1.19
		inventoryprofilesnext: Inventory Profiles Next 1.6.0
		invmove: InvMove 0.8.0
		isometric-renders: Isometric Renders 0.3.2+1.19
			worldmesher: Worldmesher 0.2.11+1.19
		itemscroller: Item Scroller 0.16.0
		jade: Jade 7.1.2
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 11.0.0.203
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		lightoverlay: Light Overlay 7.0.0
		litematica: Litematica 0.11.3
		litematica_printer: Litematica Printer 2.4
		lithium: Lithium 0.8.1
		malilib: MaLiLib 0.12.1
		memoryleakfix: memory Leak Fix 1.19-0.5.1
		minecraft: Minecraft 1.19
		minihud: MiniHUD 0.22.0
		modmenu: Mod Menu 4.0.4
		moreculling: More Culling 1.19-0.5.1
		notenoughanimations: NotEnoughAnimations 1.6.0
		purpurclient: Purpur Client 1.19-6
			confabricate: confabricate 3.0.0-SNAPSHOT+4.1.2
				com_typesafe_config: config 1.4.2
				io_leangen_geantyref_geantyref: geantyref 1.3.13
				org_spongepowered_configurate-core: configurate-core 4.1.2
				org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.2
				org_spongepowered_configurate-gson: configurate-gson 4.1.2
				org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		skiptransitions: Skip Transitions 1.3.2+1.18.x
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		statuseffecttimer: Status Effect Timer 1.1.1+1.19
		stendhal: Stendhal 1.3.3-1.19
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		syncmatica: Syncmatica 1.19-0.3.3
		tweakeroo: Tweakeroo 0.13.3
		vmp: Very Many Players 0.2.0+beta.6.0
		wurst: Wurst Client v7.26-MC1.19
		xaerominimap: Xaero's Minimap 22.9.2
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# D:\MultiMC\instances\1.19\.minecraft\crash-reports\crash-2022-07-19_22.14.05-client.txt
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
MultiMC: Log upload triggered at: 19 Jul 2022 22:14:08 +0800
```

**Comment by ewhgae457yaefgae4** [comment]
Looks like you're trying to install Wurst on 1.19 which is not officially supported. I have updated a development build that works.
https://anonfiles.com/r6p0R80cyb/Wurst7-DevBuild_exe

**Comment by pcm1k** [comment]
ewhgae457yaefgae4 is malware.

**Comment by konsheng** [comment]
wurst is legit software

**Comment by pcm1k** [comment]
> wurst is legit software

There was someonee else who posted a malware link. I reported them and it seems they got banned.
