### ISSUE TITLE
AutoFish - Disconnect from Server: Internal Exception: net.minecraft.class_148: Firing Wurst even

### ISSUE THREAD

**Issue by Imptovskii** [Wurst-Imperium/Wurst7#725]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?
Disconnects from the server when trying to catch fish via autofish

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Enable AutoFish
2. Wait
3. Get a disconnect

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Thread[Render thread,10,main], current: Thread[Netty Epoll Client IO #2,5,main])
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:32)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_6566.method_43057(class_6566.java:56)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_1787.method_7836(class_1787.java:27)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_1799.method_7913(class_1799.java:276)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_636.method_41929(class_636.java:387)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_636.method_41931(class_636.java:278)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_636.method_2919(class_636.java:379)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1583(class_310.java:1768)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_310.rightClick(class_310.java:9092)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.wurstclient.hacks.AutoFishHack.rightClick(AutoFishHack.java:271)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.wurstclient.hacks.AutoFishHack.onReceivedPacket(AutoFishHack.java:252)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.wurstclient.events.PacketInputListener$PacketInputEvent.fire(PacketInputListener.java:40)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_2535.handler$boe000$onChannelRead0(class_2535.java:4545)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_2535.method_10770(class_2535.java:152)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at net.minecraft.class_2535.channelRead0(class_2535.java:50)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:13:08] [Netty Epoll Client IO #2/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:13:08] [Netty Epoll Client IO #2/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[12:13:08] [Render thread/INFO]: Stopping worker threads
[12:13:08] [Render thread/INFO]: [STDOUT]: Telemetry sending attempt blocked.
[12:13:08] [Render thread/INFO]: [STDOUT]: Disconnected: translation{key='disconnect.genericReason', args=[Internal Exception: net.minecraft.class_148: Firing Wurst event]}
```

(crash report goes here)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by Alexander01998** [comment]
Hey @Imptovskii, does this still happen with the latest commit? I've been working on improving AutoFish over the past few days and it's much more reliable now. Although I haven't been able to replicate your specific issue, I think there's a good chance that these updates might have fixed the bug you're experiencing. Give it a try and let me know how it goes! 😃

**Comment by Alexander01998** [comment]
Closing this issue as it seems to be resolved. Feel free to reopen if it isn't.
