### ISSUE TITLE
When I update hack.jar and restart MC, it prompts me: console log

### ISSUE THREAD

**Issue by baneddddaccount** [Wurst-Imperium/Wurst7#730]
## Description
first,I am outgoing player.
i would like to post error report 
here is my [log](https://www.dropbox.com/s/35ghu8dpjkq3icv/minecraft-exported-crash-info-2022-11-05T18-44-33.rar?dl=0)

## Steps To Reproduce
1. delete  Wurst about old version
2. add new Wurst to folder named mod
3. launch MC game

## Crash Report
[main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod wurst
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.10.jar:?]
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285) ~[access-widener-2.1.0.jar:?]
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84) ~[access-widener-2.1.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439) ~[fabric-loader-0.14.10.jar:?]
	... 3 more

this info without otherside notes.

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by Alexander01998** [comment]
Looking at the logs, it seems like you put the sources jar into your mods folder.
The sources jar is only for reading the source code and cannot be launched.
You need to use the regular "Wurst-Client-v7.30-MC1.19.2.jar" file without any "-sources" or "-dev" at the end.

**Comment by baneddddaccount** [comment]
Oh, thank you so much, it really worked. Great author uw and your reply is so fast that i can not trust u
