### ISSUE TITLE
Provider "jar" not found

### ISSUE THREAD

**Issue by xzjplaygame** [Wurst-Imperium/Wurst7#731]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?My game crashed.

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. Install Minecraft 1.19 and Fabric 0.14.10
2. Install Fabric API and Wurstclient7
3. Start game

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.
![error](https://user-images.githubusercontent.com/107248117/200163432-b3ce2e4f-40d3-4398-9391-93daa7da4773.png)

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.
```
Uncaught exception in thread "main"
java.nio.file.ProviderNotFoundException: Provider "jar" not found
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:359)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:113)
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:47)
	at net.fabricmc.tinyremapper.OutputConsumerPath$Builder.build(OutputConsumerPath.java:76)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:294)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:238)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:313)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by Alexander01998** [comment]
Please post a screenshot of your mods folder.
