### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by ilpiruz** [Wurst-Imperium/Wurst7#782]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. build the wurst jar from source code
2. open it (i used multi mc)
3. and it will crash

## Screenshots / Videos (Optional)
If applicable, add screenshots, videos or other files to help explain the problem.

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

(crash report goes here)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by Alexander01998** [comment]
I'm sorry, but this is not a useful bug report. You haven't provided any crash reports or log files and I don't even know what version you're using. I've tried launching the latest release in MultiMC just now and it works perfectly fine.

**Comment by ilpiruz** [comment]
MultiMc crash log:
Failed to find Minecraft main class:
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:188)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
