### ISSUE TITLE
AutoLibrarian - The game crashes when cramming in the same block where the librarian is

### ISSUE THREAD

**Issue by f1refa11** [Wurst-Imperium/Wurst7#787]
Before posting, please make sure that this hasn't already been reported by someone else.

## Description
What's wrong?
The game crashes when cramming in the same block where the librarian is, AutoLibrarian hack

## Steps To Reproduce
Please make a list of steps to reproduce the problem (ideally from a fresh Wurst installation):
1. go to any multiplayer server
2. turn on the AutoLibrarian hack
3. wait for the villager to stop
4. go to the same position where the villager is
5. crash

## Screenshots / Videos (Optional)

https://user-images.githubusercontent.com/58619409/222803304-3d99bbe2-65db-4516-a201-176608888de3.mp4

## Crash Report
Please find your crash report file at "%appdata%/.minecraft/crash-reports", open the file in a text editor and copy-paste its content below.

```

[21:39:27] [Render thread/INFO]: [STDERR]: java.util.NoSuchElementException: No value present
[21:39:27] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.Optional.get(Unknown Source)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.wurstclient.hacks.AutoLibrarianHack.openTradeScreen(AutoLibrarianHack.java:390)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.wurstclient.hacks.AutoLibrarianHack.onUpdate(AutoLibrarianHack.java:193)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.wurstclient.events.UpdateListener$UpdateEvent.fire(UpdateListener.java:27)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$del004$onTick(class_746.java:3865)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_5773(class_746.java:218)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_638.method_18646(class_638.java:269)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1937.method_18472(class_1937.java:482)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_638.method_32124(class_638.java:252)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_638.method_18116(class_638.java:248)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1574(class_310.java:1885)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1150)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:781)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.method_44604(Main.java:244)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:51)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[21:39:27] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[21:39:27] [Render thread/INFO]: Disconnect from ....
[21:39:27] [Render thread/INFO]: UDP closed
[21:39:27] [Input Device Recorder/INFO]: Recorder cleanup
[21:39:27] [Input Device Recorder/INFO]: Close opus encoder
[21:39:27] [Render thread/INFO]: Stopping JEI
[21:39:27] [Render thread/INFO]: Stopping JEI
[21:39:27] [Render thread/INFO]: Sending Runtime Unavailable...
[21:39:27] [Render thread/INFO]: Stopping JEI GUI
[21:39:27] [Render thread/INFO]: Sending Runtime Unavailable took 186.4 μs
[21:39:27] [Render thread/INFO]: Stopping worker threads
[21:39:27] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Firing Wurst event
	at net.minecraft.class_1937.method_18472(class_1937.java:489) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_32124(class_638.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:248) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1885) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1150) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[Fabric%201.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[Fabric%201.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.13.jar:?]
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source) ~[?:?]
	at net.wurstclient.hacks.AutoLibrarianHack.openTradeScreen(AutoLibrarianHack.java:390) ~[Wurst-Client-v7.32-MC1.19.3.jar:?]
	at net.wurstclient.hacks.AutoLibrarianHack.onUpdate(AutoLibrarianHack.java:193) ~[Wurst-Client-v7.32-MC1.19.3.jar:?]
	at net.wurstclient.events.UpdateListener$UpdateEvent.fire(UpdateListener.java:27) ~[Wurst-Client-v7.32-MC1.19.3.jar:?]
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69) ~[Wurst-Client-v7.32-MC1.19.3.jar:?]
	at net.wurstclient.event.EventManager.fire(EventManager.java:42) ~[Wurst-Client-v7.32-MC1.19.3.jar:?]
	at net.minecraft.class_746.handler$del004$onTick(class_746.java:3865) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_5773(class_746.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18646(class_638.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:482) ~[client-intermediary.jar:?]
	... 11 more
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-03-03 21:39:27
Description: Firing Wurst event

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Unknown Source)
	at net.wurstclient.hacks.AutoLibrarianHack.openTradeScreen(AutoLibrarianHack.java:390)
	at net.wurstclient.hacks.AutoLibrarianHack.onUpdate(AutoLibrarianHack.java:193)
	at net.wurstclient.events.UpdateListener$UpdateEvent.fire(UpdateListener.java:27)
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_746.handler$del004$onTick(class_746.java:3865)
	at net.minecraft.class_746.method_5773(class_746.java:218)
	at net.minecraft.class_638.method_18646(class_638.java:269)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)
	at net.minecraft.class_310.method_1574(class_310.java:1885)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Optional.get(Unknown Source)
	at net.wurstclient.hacks.AutoLibrarianHack.openTradeScreen(AutoLibrarianHack.java:390)
	at net.wurstclient.hacks.AutoLibrarianHack.onUpdate(AutoLibrarianHack.java:193)
	at net.wurstclient.events.UpdateListener$UpdateEvent.fire(UpdateListener.java:27)
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_746.handler$del004$onTick(class_746.java:3865)
	at net.minecraft.class_746.method_5773(class_746.java:218)
	at net.minecraft.class_638.method_18646(class_638.java:269)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)

-- Affected event --
Details:
	Event class: net.wurstclient.events.UpdateListener$UpdateEvent
Stacktrace:
	at net.wurstclient.event.EventManager.fireImpl(EventManager.java:69)
	at net.wurstclient.event.EventManager.fire(EventManager.java:42)
	at net.minecraft.class_746.handler$del004$onTick(class_746.java:3865)
	at net.minecraft.class_746.method_5773(class_746.java:218)
	at net.minecraft.class_638.method_18646(class_638.java:269)
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)
	at net.minecraft.class_310.method_1574(class_310.java:1885)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 366988
	Entity Name: FireFall__
	Entity's Exact location: 1428.66, 21.00, 378.46
	Entity's Block location: World: (1428,21,378), Section: (at 4,5,10 in 89,1,23; chunk contains blocks 1424,-64,368 to 1439,319,383), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,-64,0 to 1535,319,511)
	Entity's Momentum: 0.03, -0.08, 0.11
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:482)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)
	at net.minecraft.class_310.method_1574(class_310.java:1885)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Please note:** If the game did not crash, please hold down F3+C for 10 seconds to generate a crash report. Even when a bug doesn't cause the game to crash, this file still contains useful information that can help us to find and fix the problem. Because of this, please always include a crash report.

**Comment by Alexander01998** [comment]
I see. When you're inside the villager, it fails to calculate a hit vector for right-clicking on that same villager. Makes me wonder what happens in vanilla when you right-click an entity while being inside it.

Right now I'm busy porting Wurst 7.32 to 1.19.2, but I'll do some testing on this later and get a bugfix out for the next update.

**Comment by bendy1234** [comment]
> I see. When you're inside the villager, it fails to calculate a hit vector for right-clicking on that same villager. Makes me wonder what happens in vanilla when you right-click an entity while being inside it.
> 
> Right now I'm busy porting Wurst 7.32 to 1.19.2, but I'll do some testing on this later and get a bugfix out for the next update.

In vanilla `ProjectileUtil.raycast` is used to find the entity the player is looking at
