### ISSUE TITLE
Wurst for 20w12a crashes

### ISSUE THREAD

**Issue by MMK21Hub** [Wurst-Imperium/Wurst7#82]
## Description
Wurst crashes whilst initializing game.

## Steps to reproduce
1. Download and install the latest version of wurst
2. Press play
3. Wait for a bit
4. ❌: Game crashes.

## Versions
Please complete the following information:
- Minecraft version: 20w12a
- Wurst version: 7.1.2

## Crash report
```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 24/03/20 06:56
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2378.<clinit>(class_2378.java:81)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:393)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-object-builders-v0.mixins.json:MixinBlock] from phase [DEFAULT] in config [fabric-object-builders-v0.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> fabric-object-builders-v0.mixins.json:MixinBlock -> Apply Methods -> (Lnet/minecraft/class_2248$class_2251;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$zga000$init -> Transform LVT -> var=builder -> desc=Lnet/minecraft/class_2248$class_2251;]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:490)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:523)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:509)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 17 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.class_2248$class_2251
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:938)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:909)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:449)
	... 24 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2378.<clinit>(class_2378.java:81)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:393)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 20w12a
	Minecraft Version ID: 20w12a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 67281392 bytes (64 MB) / 167772160 bytes (160 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.5.3+build.308-1.16
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d3d
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.1+b7d52fa53d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893d
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.6+0aae0f413d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d3d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3d
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+b17265713d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+04b997943d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d3d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.9+5b8a535a3d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d63d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.6+2f56dff23d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+5b8a535a3d
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d63d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.4+9421522d3d
		fabric-networking-v0: Fabric Networking (v0) 0.1.8+9421522d3d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.4+b7d52fa53d
		fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d63d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.7+9421522d3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.11+2f56dff23d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.25+2f56dff23d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a603d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d3d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed93d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104903d
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104903d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.12+5b8a535a3d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915803d
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba73d
		fabricloader: Fabric Loader 0.7.8+build.189
		minecraft: Minecraft 1.16-alpha.20.12.a
		wurst: Wurst Client v7.1.2-MC20w12a
	Launched Version: fabric-loader-0.7.8+build.189-20w12a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

```

**Comment by Alexander01998** [comment]
The game is crashing because you are using an outdated Fabric API version that doesn't support Minecraft 20w12a. You need this version instead: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2904848

**Comment by MMK21Hub** [comment]
> The game is crashing because you are using an outdated Fabric API version that doesn't support Minecraft 20w12a. You need this version instead: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2904848

Thanks! I will remember to update Fabric API in the Future. Closing.
